### ISSUE TITLE
latent me demo - error

### ISSUE THREAD

**Issue by paulnicholas** [googlecolab/colabtools#1157]
Bug report for Colab: http://colab.research.google.com/.

I hope this is the right venue for this issue.

- Describe the current behavior:
I am on the colab Latent Me.ipynb demo. Running the cell
!python encode_images.py aligned_images/ generated_images/ latent_representations/ --iterations 1000
gives the following error:

2020-04-16 22:04:32.518618: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "encode_images.py", line 8, in <module>
    import dnnlib.tflib as tflib
  File "/content/stylegan/stylegan/dnnlib/tflib/__init__.py", line 8, in <module>
    from . import autosummary
  File "/content/stylegan/stylegan/dnnlib/tflib/autosummary.py", line 31, in <module>
    from . import tfutil
  File "/content/stylegan/stylegan/dnnlib/tflib/tfutil.py", line 34, in <module>
    def shape_to_list(shape: Iterable[tf.Dimension]) -> List[Union[int, None]]:
AttributeError: module 'tensorflow' has no attribute 'Dimension'

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1r3hc9MF4uodpoBYz9LoJWCvZhyUebhXC

**Comment by craigcitro** [comment]
You should report this on the repo where you found that notebook.
