### ISSUE TITLE
issue in downloading the course 

### ISSUE THREAD

**Issue by 1-owo-1** [googlecolab/colabtools#1420]
after running "Run this Cell to Download Skillshare Course"
this appears:
Traceback (most recent call last):
  File "/root/.skillshare-1hack/dl.py", line 50, in <module>
    main()
  File "/root/.skillshare-1hack/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.skillshare-1hack/skillshare.py", line 29, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.skillshare-1hack/skillshare.py", line 32, in download_course_by_class_id
    data = self.fetch_course_data_by_class_id(class_id=class_id)
  File "/root/.skillshare-1hack/skillshare.py", line 69, in fetch_course_data_by_class_id
    assert res.status_code == 200, 'Fetch error, code == {}'.format(res.status_code)
AssertionError: Fetch error, code == 403

im using opera i tryied

**Comment by katlyn-edwards** [comment]
I'd recommend filing an issue in the repo where you found the notebook.
