### ISSUE TITLE
find this OSError

### ISSUE THREAD

**Issue by sharysky** [googlecolab/colabtools#1429]
Traceback (most recent call last):
  File "/content/drive/My Drive/DeepFaceLab/DeepFaceLab_Colab/mainscripts/Merger.py", line 52, in main
    cpu_only=cpu_only)
  File "/content/drive/My Drive/DeepFaceLab/DeepFaceLab_Colab/models/ModelBase.py", line 143, in __init__
    model_data = pickle.loads ( self.model_data_path.read_bytes() )
  File "/usr/lib/python3.6/pathlib.py", line 1190, in read_bytes
    return f.read()
OSError: [Errno 5] Input/output error

Done.

**Comment by craigcitro** [comment]
We're seeing drive API errors; follow #1428 for progress.

**Comment by sharysky** [comment]
Would you tell me what can I do?Thank you Very much.
