### ISSUE TITLE
RuntimeError: DataLoader worker (pid 742) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

### ISSUE THREAD

**Issue by ahmedsnoun** [googlecolab/colabtools#1857]
I am using pytorch 1.7.0  in Colab.

I often get this error:

**RuntimeError: DataLoader worker (pid 742) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.**

      ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
      �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
      �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
      �Traceback (most recent call last):
        File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
          data = self._data_queue.get(timeout=timeout)
        File "/usr/lib/python3.6/multiprocessing/queues.py", line 104, in get
          if not self._poll(timeout):
        File "/usr/lib/python3.6/multiprocessing/connection.py", line 257, in poll
          return self._poll(timeout)
        File "/usr/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
          r = wait([self], timeout)
        File "/usr/lib/python3.6/multiprocessing/connection.py", line 911, in wait
          ready = selector.select(timeout)
        File "/usr/lib/python3.6/selectors.py", line 376, in select
          fd_event_list = self._poll.poll(timeout)
        File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
          _error_if_any_worker_fails()
      RuntimeError: DataLoader worker (pid 742) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/content/drive/My Drive/NTURGB+D/st_gcn/main.py", line 36, in <module>
          p.start()
        File "/content/drive/My Drive/NTURGB+D/st_gcn/processor/processor_2.py", line 185, in start
          self.train()
        File "/content/drive/My Drive/NTURGB+D/st_gcn/processor/recognition_2.py", line 52, in train
          for data, label in loader:
        File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 435, in __next__
          data = self._next_data()
        File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
          idx, data = self._get_data()
        File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
          success, data = self._try_get_data()
        File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
          raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
      RuntimeError: DataLoader worker (pid(s) 742, 745) exited unexpectedly

Is there any solution for this? can you tell me how to increase the shared memory?

**Comment by shakeebmurtaza** [comment]
I am facing the similar issue even on Colab Pro++
