### ISSUE TITLE
Incorrect Python 3.7 Distribution Class: dataclasses.py

### ISSUE THREAD

**Issue by garricklw** [googlecolab/colabtools#1876]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

Colab seems to be using a Python 3.7 by default now however, the dataclasses.py file is not the same file that should be distributed with Python 3.7.10. My code is throwing the following error:

  File "/usr/local/lib/python3.7/dist-packages/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'

I have verified that there is no _ClassVar attribute in the Python 3.7 typing module. The same method '_is_classvar' is in the correct dataclasses.py and refers instead to 'typing.ClassVar'. 

I have tried factory resetting the notebook runtime however, the issue persists. I was able to work around the issue by replacing the dataclasses.py with the correct one.

[dataclasses_wrong.txt](https://github.com/googlecolab/colabtools/files/6039012/dataclasses_wrong.txt)
[dataclasses_correct.txt](https://github.com/googlecolab/colabtools/files/6039013/dataclasses_correct.txt)

(Empty notebook but the files are still wrong, probably has more to do with the runtime than anything)
https://colab.research.google.com/drive/1Sgqex1DdxmbOXwPMNezFnsSKXlJYtrKu?usp=sharing

**Comment by colaboratory-team** [comment]
Do you know why you're getting dataclasses loaded from /usr/local/lib and not /usr/lib ?
On a freshly-factory-reset VM I see:
![](https://user-images.githubusercontent.com/38081706/109071671-e1371980-76a8-11eb-95db-7bd7c8bc6fb0.png)

**Comment by garricklw** [comment]
It must have something to do with raytune. I'm installing as in the screenshot, the full stacktrace is below:

2021-02-24 22:10:30,671	WARNING worker.py:1107 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 55ecd27aff6f4d98f241b5ef01000000. Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/function_manager.py", line 496, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/__init__.py", line 2, in <module>
    from ray.tune.tune import run_experiments, run
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/tune.py", line 13, in <module>
    from ray.tune.ray_trial_executor import RayTrialExecutor
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/ray_trial_executor.py", line 17, in <module>
    from ray.tune.durable_trainable import DurableTrainable
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/durable_trainable.py", line 5, in <module>
    from ray.tune.syncer import get_cloud_sync_client
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/syncer.py", line 89, in <module>
    @dataclass
  File "/usr/local/lib/python3.7/dist-packages/dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "/usr/local/lib/python3.7/dist-packages/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/lib/python3.7/dist-packages/dataclasses.py", line 801, in _process_class
    for name, type in cls_annotations.items()]
  File "/usr/local/lib/python3.7/dist-packages/dataclasses.py", line 801, in <listcomp>
    for name, type in cls_annotations.items()]
  File "/usr/local/lib/python3.7/dist-packages/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/usr/local/lib/python3.7/dist-packages/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'


![image](https://user-images.githubusercontent.com/52170140/109073018-d178fe80-76c3-11eb-8a9f-6b43b91ce08a.png)

**Comment by garricklw** [comment]
Screenshot of stack trace is probably more readable: 
![image](https://user-images.githubusercontent.com/52170140/109073159-04bb8d80-76c4-11eb-81c9-a39a89504232.png)

**Comment by craigcitro** [comment]
Thanks for the details! Here's what's happening: we're accidentally picking up `dataclasses==0.6` as a dep of another library we install. I'm going to do a little work on our side to remove it, since (with 3.7) there's no need to have it installed at all. TBH, I'm not 100% clear on how you're ending up with the wrong version when importing, but given that we want to remove it anyway, I may let that mystery remain.

Fix will land soon, but in the interim, an easy workaround: slap a `!yes | pip uninstall dataclasses` before your other installs and you're back in action.

**Comment by garricklw** [comment]
Thanks so much for all of the quick replies, I'll give the workaround a try later today. I'll leave the bug report open in case you want to use it to track the bad import, I assume you can close it whenever you want.

**Comment by craigcitro** [comment]
OK, should be fixed!
