### ISSUE TITLE
Variable inspector works sporadically

### ISSUE THREAD

**Issue by carlykleinstern** [googlecolab/colabtools#2472]
I would like to use the Variable Inspector. If I do:
`x=10`
Then the Inspector updates as expected.

If I try to load in a .sav file from IDL:
```
from scipy.io import readsav
import numpy as np

tab = readsav('/content/drive/MyDrive/data_n2o_small.sav')
n2o_ar = np.array(tab['dat'])
print(n2o_ar)
```

The variable inspector does not update, and instead reads "error":

```
Type:<error>
Value:Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 671, in internal_get_variable_json variables.append(child_var.get_var_data(fmt=fmt)) File "/usr/local/lib/python3.7/dist-packages/google/colab/_debugpy_repr.py", line 30, in _get_var_data shape = get_shape(self.value) File "/usr/local/lib/python3.7/dist-packages/google/colab/_debugpy_repr.py", line 54, in get_shape shape = getattr(obj, 'shape', None) File "/usr/local/lib/python3.7/dist-packages/scipy/io/idl.py", line 655, in __getitem__ return super(AttrDict, self).__getitem__(name.lower()) KeyError: 'shape'

 File "<ipython-input-12-b5986a1cec56>", line 1
    <error>
    ^
SyntaxError: invalid syntax

```
System:
I'm using Safari on a Mac with Catalina (10.15.7) operating system.

The example file can be found here: https://drive.google.com/file/d/1Ii5YOnBWYEIUMZU6gMOiUFGwdSgI_koa/view?usp=sharing

Thanks for any help!

**Comment by blois** [comment]
Thanks for the great bug!

Simplified repro:

```python
from google.colab import _debugpy_repr
import scipy.io
d = scipy.io.idl.AttrDict()
_debugpy_repr.get_shape(d)
```

We'll try to get a fix out shortly.

**Comment by carlykleinstern** [comment]
@blois It works now. Thank you!

**Comment by blois** [comment]
The fix for this should now be in prod. Thanks again for the report.

**Comment by carlykleinstern** [comment]
Thanks again. :)
