### ISSUE TITLE
running local google colab returns multyple error

### ISSUE THREAD

**Issue by DorHerbesman** [googlecolab/colabtools#2608]
Hello all!
I have a problem when I'm trying to assert local runtime for google collab through jupyter.
i made a script containing this:

jupyter notebook \
  --NotebookApp.allow_origin='https://colab.research.google.com' \
  --port=8888 \
  --NotebookApp.port_retries=0
  
when putting the local+token in google colab i get this error:

ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\dorh1\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\dorh1\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "C:\Users\dorh1\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "C:\ProgramData\Anaconda3\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
Traceback (most recent call last):
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 452, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 481, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\dorh1\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\dorh1\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "C:\Users\dorh1\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "C:\ProgramData\Anaconda3\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dorh1\AppData\Roaming\Python\Python38\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\dorh1\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x0000021D48C9DAF0>)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 452, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 481, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\dorh1\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\dorh1\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "C:\Users\dorh1\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "C:\ProgramData\Anaconda3\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 314, in run_forever
    assert self._self_reading_future is None
AssertionError
[E 09:49:07.522 NotebookApp] Uncaught error when proxying request
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 446, in _get_proxied_ws
        client = yield self._proxied_ws_future
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 436, in _on_open
        client = yield websocket.websocket_connect(
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
    tornado.simple_httpclient.HTTPTimeoutError: Timeout during request
[E 09:49:07.524 NotebookApp] Uncaught error when proxying request
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 446, in _get_proxied_ws
        client = yield self._proxied_ws_future
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 446, in _get_proxied_ws
        client = yield self._proxied_ws_future
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 436, in _on_open
        client = yield websocket.websocket_connect(
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
    tornado.simple_httpclient.HTTPTimeoutError: Timeout during request
[E 09:49:07.527 NotebookApp] Uncaught error when proxying request
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 446, in _get_proxied_ws
        client = yield self._proxied_ws_future
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 446, in _get_proxied_ws
        client = yield self._proxied_ws_future
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 446, in _get_proxied_ws
        client = yield self._proxied_ws_future
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 436, in _on_open
        client = yield websocket.websocket_connect(
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
    tornado.simple_httpclient.HTTPTimeoutError: Timeout during request
[E 09:49:07.528 NotebookApp] Uncaught error when proxying request
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 446, in _get_proxied_ws
        client = yield self._proxied_ws_future
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 446, in _get_proxied_ws
        client = yield self._proxied_ws_future
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 446, in _get_proxied_ws
        client = yield self._proxied_ws_future
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 446, in _get_proxied_ws
        client = yield self._proxied_ws_future
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_http_over_ws\handlers.py", line 436, in _on_open
        client = yield websocket.websocket_connect(
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
    tornado.simple_httpclient.HTTPTimeoutError: Timeout during request

I have tried to update/reinstall tornado, conda, and jupyer.
any other tips?

**Comment by craigcitro** [comment]
Do you get an error in the UI when this connection failure happens? Can you include a screenshot of the full dialog?

We have a dialog that does some diagnostics here, which triggers when you hit "Troubleshoot" on the connection failure, and looks like this: 
<img width="712" alt="image" src="https://user-images.githubusercontent.com/468559/153506651-5e2e1b3c-6538-4c5a-8ff0-61fa055ae205.png">
