### ISSUE TITLE
Colab notebook becomes unresponsive.

### ISSUE THREAD

**Issue by davidshumway** [googlecolab/colabtools#2737]
**Describe the current behavior**
Colab notebook becomes unresponsive. The page doesn't freeze but it's not possible to run a cell. Cells can be interrupted but running a cell again doesn't do anything. Occasionally, this error appears: `OSError: [Errno 107] Transport endpoint is not connected`.

Background: Mounting Google Drive. Then use `pandas.read_csv('file2.csv')`. This is okay.

But issue is here:

```python
print('start')
with open('test1.abc', 'w') as f:
  f.write("test")
with open('test3.abc', 'w') as f:
  f.write("test")
with open('test3.abc', 'w') as f:
  f.write("test")

df1 = pd.read_csv('file1.csv')

with open('./test1.abc', 'a') as f:
    np.savetxt(f, df1.values, fmt='''
%s %s %s
''')
with open('./test2.abc', 'a') as f:
    np.savetxt(f, x.values, fmt='''
%s %s %s
''')

print('loading file.csv')

# hangs reading this file
df2 = pd.read_csv('file2.csv')
print('here')

with open('./test3.abc', 'a') as f:
    np.savetxt(f, x.values, fmt='''
%s %s %s
''')
```

"loading file.csv'" is printed but "here" is never printed. The CSV files are very small and typically load immediately. But in this case, it's stuck apparently loading `df2 = pd.read_csv('file2.csv')`. Also, test1 and test2 have text appended to their files, but test3 never changes.

This behavior is sporadic. Sometimes the notebook runs fine. Occasionally, it hangs during a procedure such as given above. When this occurs, I've tried changing browsers, restarting the runtime, changing runtime type from gpu to cpu or vice versa, and factory reset runtime. I've tried hard-refreshing the page (ctrl+shift+r). I've also tried terminating all sessions using the manage sessions dialog.

**Describe the expected behavior**
Should load the file and finish writing `test3.abc`.

**What web browser you are using**
Tried in Chrome and Firefox.

**Additional context**

**Comment by cperry-goog** [comment]
Can you share a self contained minimally reproducible notebook?

**Comment by davidshumway** [comment]
I don't think sharing a notebook would be helpful. This unresponsive behaviour happens sporadically in all of my (roughly 10-20) notebooks. I don't think it's any code in particular. I'm guessing it's a combination of a lot of data mounted in my Google Drive (400GB or so). I'll also say that most of my notebooks are fairly long as I used the heading-collapse feature to hide a lot of previous experiments. For example, a notebook I'm using at the moment (which just had this issue a few times in a row -- notebook hangs during processing a set of cells, I restart the notebook, it happens again) is >3MB when downloaded in .ipynb format.

By default I also mount my drive first in all of my notebooks. Occasionally, the notebook fails with the response: ```OSError: [Errno 107] Transport endpoint is not connected```. Usually, the notebook hangs on some simple procedure, such as a opening a file (`with open('file', 'w') as f: ... `). Sometimes I wait for ten minutes or so and do something else, assuming that the process will eventually finish. Usually in this case I return 10 minutes later and the process and still there in the same cell with the little green arrow pointing to the same line as it was when I left 10 minutes before.

**Comment by davidshumway** [comment]
Example error, which is happening when running on both None and GPU:

```bash
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-0078c10f2160>", line 3, in <module>
    with open('./obs.n3','w') as f:
OSError: [Errno 107] Transport endpoint is not connected: './BEACON-obs.n3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 1823, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'OSError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.7/inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.7/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.7/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.7/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.7/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected

```

**Comment by davidshumway** [comment]
And a slightly different version of the above error.

```bash
ERROR:root:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 0))

ERROR:root:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 0))

---------------------------------------------------------------------------

OSError                                   Traceback (most recent call last)

[<ipython-input-3-90cc8ca65586>](https://localhost:8080/#) in <module>()
     13 ex:type "A"^^xsd:string .
---> 14 ''')
     15 get_ipython().system('tail obs.n3')

<__array_function__ internals> in savetxt(*args, **kwargs)

2 frames

[/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py](https://localhost:8080/#) in savetxt(fname, X, fmt, delimiter, newline, header, footer, comments, encoding)
   1439                                     % (str(X.dtype), format)) from e
-> 1440                 fh.write(v)
   1441 

[/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py](https://localhost:8080/#) in write_normal(self, v)
   1351         def write_normal(self, v):
-> 1352             self.fh.write(asunicode(v))
   1353 

OSError: [Errno 107] Transport endpoint is not connected


During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)

OSError: [Errno 107] Transport endpoint is not connected


During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)

[<ipython-input-3-90cc8ca65586>](https://localhost:8080/#) in <module>()
     12 sosa:hasSimpleResult "%s"^^xsd:double ;
     13 ex:type "A"^^xsd:string .
---> 14 ''')
     15 get_ipython().system('tail obs.n3')

OSError: [Errno 107] Transport endpoint is not connected
```

Where the relevant code snippet is:

```python
with open('./BEACON-obs.n3','w') as f:
  f.write("init")
  a = x[['ActivityIdentifier', 'MonitoringLocationIdentifier', 'time', 'p']].copy()
  np.savetxt(f, a.values, fmt='''
ex:obs-%s a sosa:Observation ;
sosa:hasFeatureOfInterest ex:FOI-%s ;
sosa:resultTime "%s"^^xsd:dateTime ;
sosa:observedProperty "A"^^xsd:string ;
sosa:hasSimpleResult "%s"^^xsd:double ;
ex:type "A"^^xsd:string .
''')
!tail obs.n3
```

**Comment by davidshumway** [comment]
After failing to run this code numerous times, it appears changing the `.copy()` code to outside of the `with` block succeeds. 

```python
a = x[['ActivityIdentifier', 'MonitoringLocationIdentifier', 'time', 'p']].copy()
with open('./BEACON-obs.n3','w') as f:
  f.write("init")
  np.savetxt(f, a.values, fmt='''
ex:obs-%s a sosa:Observation ;
sosa:hasFeatureOfInterest ex:FOI-%s ;
sosa:resultTime "%s"^^xsd:dateTime ;
sosa:observedProperty "A"^^xsd:string ;
sosa:hasSimpleResult "%s"^^xsd:double ;
ex:type "A"^^xsd:string .
''')
```

**Comment by davidshumway** [comment]
Unsure if that's a bug?

**Comment by davidshumway** [comment]
This is actually the same as this one: https://github.com/googlecolab/colabtools/issues/3136
