### ISSUE TITLE
tf_records.py file not opening.

### ISSUE THREAD

**Issue by Aarshhh** [googlecolab/colabtools#2935]
On running the code below(considering that I have already uploaded generate_tfrecords.py file in drive):
#For train.record
!python /mydrive/customTF2/generate_tfrecord.py train_labels.csv  label_map.pbtxt images/ train.record

#For test.record
!python /mydrive/customTF2/generate_tfrecord.py test_labels.csv  label_map.pbtxt images/ test.record

I am getting the following error:

groups:   0% 0/32 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mydrive/customTF2/generate_tfrecord.py", line 137, in <module>
    tf_example = create_tf_example(group, path, class_dict)
  File "/mydrive/customTF2/generate_tfrecord.py", line 25, in create_tf_example
    encoded_jpg = fid.read()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 114, in read
    self._preread_check()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 77, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: images/0da4edfa-00064; No such file or directory
groups:   0% 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mydrive/customTF2/generate_tfrecord.py", line 137, in <module>
    tf_example = create_tf_example(group, path, class_dict)
  File "/mydrive/customTF2/generate_tfrecord.py", line 25, in create_tf_example
    encoded_jpg = fid.read()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 114, in read
    self._preread_check()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 77, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: images/58b33c90-00001; No such file or directory

I have tried solving this issue using multiple approaches but none of them worked as a result of which I am unable to train the model using my dataset.

I have followed exact same code and guide as per this youtube video:
https://www.youtube.com/watch?v=amURyS6CAaY

colab notebook used in this video: 
https://colab.research.google.com/drive/1QCU_dCR0ozI8j6X2btEDCsaUk5p_b1uw?usp=sharing

github used in the video containing tfrecord file:
https://github.com/techzizou/Train-Object-Detection-Model-TF-2.x

**Comment by cperry-goog** [comment]
I think you'll want to contact the notebook author; you may be hitting Drive limits as described here: https://research.google.com/colaboratory/faq.html#drive-timeout
