### ISSUE TITLE
DNN library is not found.

### ISSUE THREAD

**Issue by kevinmfreire** [googlecolab/colabtools#3008]
I am using VGG16 pre-trained model as a loss funciton and I never had an issue.  However now when I am training it today I get an error as shown below. I am not sure if there was an update or what but I can't continue with my project.

Node: 'perceptual_loss/model_3/block1_conv1/Relu'
DNN library is not found.
	 [[{{node perceptual_loss/model_3/block1_conv1/Relu}}]] [Op:__inference_train_function_63390]

Using google Chrome

**Comment by colaboratory-team** [comment]
Can you provide a minimal repro notebook that shows the error?

**Comment by kevinmfreire** [comment]
I have a class that extracted outputs of different layers within the VGG16 pretrained model as shown below:

```
class vggModel(object):
    def __init__(self, image_shape=(None, None, 3)):
        self.image_shape = image_shape
        self.vgg = VGG16(include_top=False, weights='imagenet', input_shape=self.image_shape)
        self.selectedLayers = ['block1_conv2','block2_conv2','block3_conv3','block4_conv3']
        self.selectedOutputs = [self.vgg.get_layer(i).output for i in self.selectedLayers]
        self.loss_model = Model(inputs=self.vgg.input, outputs=self.selectedOutputs)
        self.loss_model.trainable = False
        # self.mse = K.variable(value=0)
        self.mse = tf.keras.losses.MeanSquaredError()

    def perceptual_loss(self, y_true, y_pred):
        loss_value = 0
        for i in range(0,4):
            # self.mse = self.mse+ K.mean(K.square(self.loss_model(y_true)[i] - self.loss_model(y_pred)[i]))
            loss_value += self.mse(self.loss_model(y_true)[i], self.loss_model(y_pred)[i])
        return loss_value
```

This has been working for me that past few weeks without any errors.  Then yesterday It stopped and received errors as shown below.

```
Epoch 1/200
---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
[<ipython-input-45-1af035fa9b99>](https://localhost:8080/#) in <module>
      2 ###Train
      3 hist_adam = model_baf_p_mse.fit(x=data,y=[labels_3,labels_3,labels_3],batch_size=batch_size,epochs=numOfEpoch
----> 4                      ,validation_split=0, verbose=1, shuffle=True, callbacks=[model_checkpoint_callback, early_stop_callback, ClearMemory()])
      5 model_baf_p_mse.save_weights(weight_adress)

1 frames
[/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

UnimplementedError: Graph execution error:

Detected at node 'perceptual_loss/model_7/block1_conv1/Relu' defined at (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 612, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
      handle._run()
    File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 758, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1233, in inner
      self.run()
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1147, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 365, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 545, in execute_request
      user_expressions, allow_stdin,
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 306, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2855, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-45-1af035fa9b99>", line 4, in <module>
      ,validation_split=0, verbose=1, shuffle=True, callbacks=[model_checkpoint_callback, early_stop_callback, ClearMemory()])
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 890, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 949, in compute_loss
      y, y_pred, sample_weight, regularization_losses=self.losses)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/compile_utils.py", line 201, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/usr/local/lib/python3.7/dist-packages/keras/losses.py", line 139, in __call__
      losses = call_fn(y_true, y_pred)
    File "/usr/local/lib/python3.7/dist-packages/keras/losses.py", line 243, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "<ipython-input-40-2e77e1c54bd4>", line 20, in perceptual_loss
      for i in range(0,4):
    File "<ipython-input-40-2e77e1c54bd4>", line 22, in perceptual_loss
      loss_value += self.mse(self.loss_model(y_true)[i], self.loss_model(y_pred)[i])
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 490, in __call__
      return super().__call__(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 459, in call
      inputs, training=training, mask=mask)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 596, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional/base_conv.py", line 278, in call
      return self.activation(outputs)
    File "/usr/local/lib/python3.7/dist-packages/keras/activations.py", line 311, in relu
      return backend.relu(x, alpha=alpha, max_value=max_value, threshold=threshold)
    File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 4992, in relu
      x = tf.nn.relu(x)
Node: 'perceptual_loss/model_7/block1_conv1/Relu'
DNN library is not found.
	 [[{{node perceptual_loss/model_7/block1_conv1/Relu}}]] [Op:__inference_train_function_98610]
```

My training has three loss functions (perceptual, mse and ssim) and the one I am getting is the Perceptual loss function.

**Comment by colaboratory-team** [comment]
Thanks for the report, we are rolling out a fix soon. Two potential workarounds for you in the meantime:

1) !pip install -U tensorflow==2.8.2 (this one is safer)

or

2) !apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2

Make sure you Runtime -> Restart Runtime after running either of these, and your notebook should start working again

**Comment by kevinmfreire** [comment]
The issue is no longer occurring.  Whatever fix was done, thank you!
