### ISSUE TITLE
Unable to generate images. 

### ISSUE THREAD

**Issue by Stormarc2** [googlecolab/colabtools#3046]
Hi everyone,

since yesterday I'm experiencing a problem, every time I try to generate an image it says " Error not usable font ( tried arial.ttf, dejavusas.ttf) "

And the code generated is this one : 

Iteration: 1/1
100% 1/1 [00:00<00:00,  2.60it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/usr/local/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 998, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 923, in process_images
    grid = image_grid(output_images, batch_size)
  File "scripts/webui.py", line 419, in image_grid
    fnt = get_font(30)
  File "scripts/webui.py", line 401, in get_font
    raise Exception(f"No usable font found (tried {', '.join(fonts)})")
Exception: No usable font found (tried arial.ttf, DejaVuSans.ttf)

Has anyone experienced the same problem ?

Version of web browser
Firefox 
104.0.1 (64-bit)

Thanks a lot

**Comment by Stormarc2** [comment]
I tried with google chrome and it happens the same.

**Comment by cperry-goog** [comment]
Can you share a minimal repro notebook?
