### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by AlexEneas** [googlecolab/colabtools#3066]
When trying to download any Skillshare course, i get the following errors:

Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 16, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 72, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

Any help with this would be great!

**Comment by colaboratory-team** [comment]
Colab doesn't own the notebook you are using, you should reach out to the notebook author instead
