### ISSUE TITLE
Saving is not working

### ISSUE THREAD

**Issue by jonathanmm18** [googlecolab/colabtools#3300]
file saving does not work
I have this error:

```
A network error occurred and the request could not be completed.
GapiError: A network error occurred and the request could not be completed.
    at sI.fC [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/81dd28fa6e8b60b42ed5b916570ec9d7/external_polymer_binary_l10n__es.js:1446:1922)
    at new sI (https://ssl.gstatic.com/colaboratory-static/common/81dd28fa6e8b60b42ed5b916570ec9d7/external_polymer_binary_l10n__es.js:2289:233)
    at yFa (https://ssl.gstatic.com/colaboratory-static/common/81dd28fa6e8b60b42ed5b916570ec9d7/external_polymer_binary_l10n__es.js:2414:137)
    at xa.program_ (https://ssl.gstatic.com/colaboratory-static/common/81dd28fa6e8b60b42ed5b916570ec9d7/external_polymer_binary_l10n__es.js:2429:317)
    at za (https://ssl.gstatic.com/colaboratory-static/common/81dd28fa6e8b60b42ed5b916570ec9d7/external_polymer_binary_l10n__es.js:21:57)
    at xa.throw_ (https://ssl.gstatic.com/colaboratory-static/common/81dd28fa6e8b60b42ed5b916570ec9d7/external_polymer_binary_l10n__es.js:20:201)
    at Ba.throw (https://ssl.gstatic.com/colaboratory-static/common/81dd28fa6e8b60b42ed5b916570ec9d7/external_polymer_binary_l10n__es.js:22:89)
    at c (https://ssl.gstatic.com/colaboratory-static/common/81dd28fa6e8b60b42ed5b916570ec9d7/external_polymer_binary_l10n__es.js:22:343)
```

**Comment by cperry-goog** [comment]
This looks like a browser extension issue: can you try reproducing in a Chrome Incognito window?
