### ISSUE TITLE
Colab Pro+: Endpoint Not Connected after 9.5-10 Hours

### ISSUE THREAD

**Issue by Great-Bucket** [googlecolab/colabtools#3562]
Colab Pro+: Endpoint Not Connected after 9.5-10 Hours

CURRENT BEHAVIOUR:
I have been having issues deal with my Colab Pro+ account that consistently stops at about 9.5 to 10 hours. My theory is that this is happening because Google Drive is disconnecting from the colab notebook. It was suggested to me that perhaps the problem is actually with my code.  At the time I was running StyleGAN3, so perhaps it could be something in the code.  So to test this problem more thoroughly, I wrote the a very simple script that makes a calculation with the GPU and then posts a 'dummy_file' to my Google Drive every 10 minutes. (details below)

The first 'dummy_file' was written at 9:05.  The final one was written at 18:46.  This difference is 9:41. Though the script in the cell should have printed the termination time, none was printed. Instead there were a series of error messages, the last of which was 'Transport endpoint is not connected'.

For me, this is a fairly clear indication that the problem is not with my previous code, but rather there is something going on with the interplay between colab and Google Drive.

Also worth pointing out, though the cell in my script stopped running correctly after about 9.7 hours, the colab runtime continued on until 22:52 when I came home and stopped it.  That is 4 hours after the test files stopped being written to my Google Drive.  And to be clear, I double checked the resources panel before stopping the runtime, and could see that the compute units were still being consumed. So in addition this problem is not only truncating runtimes for our programs, it is also charging us for compute units that we can't utilise.

This issue is likely related to :
#3525
#3441
#3436

EXPECTED BEHAVIOUR:
My script should run for about 24 hours.  It should continue to write new 'dummy_files' every 10 min for the 24 hour duration.  When the cell stops executing it should print the termination time. When the execution stops, I should stop being charged for compute units.

WEBBROWSER:
Chrome Version 111.0.5563.146 (Official Build) (x86_64)

THIS IS my NOTEBOOK:
https://colab.research.google.com/drive/1ELsIAhXHqNQDwXiLIhQXUvtkwiMAR0Fg?usp=sharing

THIS IS THE SCRIPT:

from google.colab import drive
import torch
import time

# Mount Google Drive to '/content/drive'
drive.mount('/content/drive')

# Set the directory to use for the test
test_dir = '/content/drive/MyDrive/test_env'

# Change the current directory to the test directory
%cd "$test_dir"

# Print the execution start time
print("Execution start time:", time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))

start_time = time.time()

while True:
    x = torch.rand(10000, 10000).cuda()
    y = torch.rand(10000, 10000).cuda()
    z = torch.mm(x, y)
    del x, y, z

    # Create a file in Google Drive every 10 minutes to keep it engaged
    if time.time() - start_time > 60*10:
        # Save a dummy file to Google Drive
        filename = f"dummy_file_{time.time()}.txt"
        with open(filename, 'w') as f:
            f.write("This is a dummy file.")
        # Move the dummy file to Google Drive
        !mv "$filename" "$test_dir"

        # Update the start time
        start_time = time.time()

    # Exit the loop if 30 hours have passed
    if time.time() - start_time > 60*60*30:
        break

# Print the termination time
print("x:", time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))

///////////

THIS IS THE CELL OUTPUT:

Mounted at /content/drive
/content/drive/MyDrive/test_env
Execution start time: 2023-04-05 07:55:51
mv: 'dummy_file_1680681953.057489.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680681953.057489.txt' are the same file
mv: 'dummy_file_1680682554.4395802.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680682554.4395802.txt' are the same file
mv: 'dummy_file_1680683154.6986308.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680683154.6986308.txt' are the same file
mv: 'dummy_file_1680683756.033292.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680683756.033292.txt' are the same file
mv: 'dummy_file_1680684356.9498801.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680684356.9498801.txt' are the same file
mv: 'dummy_file_1680684957.799363.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680684957.799363.txt' are the same file
mv: 'dummy_file_1680685558.1017206.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680685558.1017206.txt' are the same file
mv: 'dummy_file_1680686158.8650804.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680686158.8650804.txt' are the same file
mv: 'dummy_file_1680686760.8771536.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680686760.8771536.txt' are the same file
mv: 'dummy_file_1680687361.2705162.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680687361.2705162.txt' are the same file
mv: 'dummy_file_1680687962.4865973.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680687962.4865973.txt' are the same file
mv: 'dummy_file_1680688563.0596695.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680688563.0596695.txt' are the same file
mv: 'dummy_file_1680689164.8267958.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680689164.8267958.txt' are the same file
mv: 'dummy_file_1680689765.2391138.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680689765.2391138.txt' are the same file
mv: 'dummy_file_1680690366.2056446.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680690366.2056446.txt' are the same file
mv: 'dummy_file_1680690966.5218568.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680690966.5218568.txt' are the same file
mv: 'dummy_file_1680691566.8661323.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680691566.8661323.txt' are the same file
mv: 'dummy_file_1680692167.3643322.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680692167.3643322.txt' are the same file
mv: 'dummy_file_1680692768.8280082.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680692768.8280082.txt' are the same file
mv: 'dummy_file_1680693369.1163409.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680693369.1163409.txt' are the same file
mv: 'dummy_file_1680693970.1939783.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680693970.1939783.txt' are the same file
mv: 'dummy_file_1680694570.326524.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680694570.326524.txt' are the same file
mv: 'dummy_file_1680695170.7438962.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680695170.7438962.txt' are the same file
mv: 'dummy_file_1680695771.1721087.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680695771.1721087.txt' are the same file
mv: 'dummy_file_1680696371.5504515.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680696371.5504515.txt' are the same file
mv: 'dummy_file_1680696974.5274715.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680696974.5274715.txt' are the same file
mv: 'dummy_file_1680697576.120631.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680697576.120631.txt' are the same file
mv: 'dummy_file_1680698176.785731.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680698176.785731.txt' are the same file
mv: 'dummy_file_1680698778.5181332.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680698778.5181332.txt' are the same file
mv: 'dummy_file_1680699378.768204.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680699378.768204.txt' are the same file
mv: 'dummy_file_1680699980.373478.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680699980.373478.txt' are the same file
mv: 'dummy_file_1680700580.5746117.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680700580.5746117.txt' are the same file
mv: 'dummy_file_1680701180.922106.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680701180.922106.txt' are the same file
mv: 'dummy_file_1680701782.147005.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680701782.147005.txt' are the same file
mv: 'dummy_file_1680702384.325012.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680702384.325012.txt' are the same file
mv: 'dummy_file_1680702984.8703878.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680702984.8703878.txt' are the same file
mv: 'dummy_file_1680703585.6976497.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680703585.6976497.txt' are the same file
mv: 'dummy_file_1680704186.466905.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680704186.466905.txt' are the same file
mv: 'dummy_file_1680704787.7346168.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680704787.7346168.txt' are the same file
mv: 'dummy_file_1680705388.2594194.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680705388.2594194.txt' are the same file
mv: 'dummy_file_1680705988.962752.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680705988.962752.txt' are the same file
mv: 'dummy_file_1680706589.2817278.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680706589.2817278.txt' are the same file
mv: 'dummy_file_1680707191.7930398.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680707191.7930398.txt' are the same file
mv: 'dummy_file_1680707792.0921884.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680707792.0921884.txt' are the same file
mv: 'dummy_file_1680708393.2316804.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680708393.2316804.txt' are the same file
mv: 'dummy_file_1680708993.632725.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680708993.632725.txt' are the same file
mv: 'dummy_file_1680709593.8979704.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680709593.8979704.txt' are the same file
mv: 'dummy_file_1680710195.0258718.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680710195.0258718.txt' are the same file
mv: 'dummy_file_1680710795.4813795.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680710795.4813795.txt' are the same file
mv: 'dummy_file_1680711396.9300683.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680711396.9300683.txt' are the same file
mv: 'dummy_file_1680711997.165539.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680711997.165539.txt' are the same file
mv: 'dummy_file_1680712599.0621312.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680712599.0621312.txt' are the same file
mv: 'dummy_file_1680713200.5898101.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680713200.5898101.txt' are the same file
mv: 'dummy_file_1680713801.3771696.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680713801.3771696.txt' are the same file
mv: 'dummy_file_1680714402.9605944.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680714402.9605944.txt' are the same file
mv: 'dummy_file_1680715003.6564124.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680715003.6564124.txt' are the same file
mv: 'dummy_file_1680715604.2444193.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680715604.2444193.txt' are the same file
mv: 'dummy_file_1680716205.925608.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680716205.925608.txt' are the same file
mv: 'dummy_file_1680716807.7304714.txt' and '/content/drive/MyDrive/test_env/dummy_file_1680716807.7304714.txt' are the same file
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-babcefe4d7bb>", line 29, in <cell line: 20>
    with open(filename, 'w') as f:
OSError: [Errno 107] Transport endpoint is not connected: 'dummy_file_1680717408.774148.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'OSError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.9/inspect.py", line 1543, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.9/inspect.py", line 1501, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.9/inspect.py", line 709, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.9/inspect.py", line 738, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.9/inspect.py", line 722, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.9/posixpath.py", line 380, in abspath
    cwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-babcefe4d7bb>", line 29, in <cell line: 20>
    with open(filename, 'w') as f:
OSError: [Errno 107] Transport endpoint is not connected: 'dummy_file_1680717408.774148.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'OSError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3575, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 2101, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1367, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1267, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1124, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 382, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.9/inspect.py", line 1543, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.9/inspect.py", line 1501, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.9/inspect.py", line 709, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.9/inspect.py", line 738, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.9/inspect.py", line 722, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.9/posixpath.py", line 380, in abspath
    cwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-babcefe4d7bb>", line 29, in <cell line: 20>
    with open(filename, 'w') as f:
OSError: [Errno 107] Transport endpoint is not connected: 'dummy_file_1680717408.774148.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'OSError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3575, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 2101, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1367, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1267, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1124, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 382, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3492, in run_ast_nodes
    self.showtraceback()
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 2101, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1367, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1267, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1142, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 382, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.9/inspect.py", line 1543, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.9/inspect.py", line 1501, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.9/inspect.py", line 709, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.9/inspect.py", line 738, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.9/inspect.py", line 722, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.9/posixpath.py", line 380, in abspath
    cwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected

</issue>

**Comment by ioritree** [comment]
@colaboratory-team please fix , we lost too many compute units !!

**Comment by EvanWiederspan** [comment]
We've gotten some reports of this from other users as well, tracking internally as b/271438583

**Comment by johnnypeck** [comment]
I've wasted a good lot of my compute MONEY ( not a fancy budget but it's what's I've got and it's mine) this past week or two due to maybe this. I don't have money to throw at a "it might work this time" service. Had a 6 hour run on Colab+ just fail again an hour ago, no files saved, no clear reason. Just disconnected about 20 minutes to being finished after 6 hours. It's happened numerous times over the past few days and seems to be escalating and happening more often. Very frustrated. I shouldn't have to need to debug my browser to to use a GPU instance.

**Comment by Warajet** [comment]
I also suffer the same problem and I still cannot figure out how to fix this problem! I lost a lot of computational units without getting my work done due to this reason! Please fix it asap!

**Comment by GeometricBCI** [comment]
On purpose? To get more money?

**Comment by hoon-bari** [comment]
@colaboratory-team Do you guys have some will to fix this problem? This problem continues almost 2 monthes but doesn't fix even now. I was a Colab Pro+ user but I quited the payment yesterday. Like upper user said, It looks like you guys don't fix this problem on purpose to get more money.

**Comment by Yanni-Chen** [comment]
Same problem: 'Transport endpoint is not connected' after running the code for a few hours several times. I have wasted more than 30 Euros without getting any results.

**Comment by silveryshine** [comment]
Encountered the same problem several times. The only thing I can do is copy all the files and models to storage space allocated by Colab, train without Google Drive, print everything I can, and pary to the Gods that the environment is still there when I reopen the notebook. Uploading training results to a thrid party storage like Github may be a good solution, but a more straightforward solution (e.g. solve the drive auto disconnect problem) is indispensable。

**Comment by luksquaresma** [comment]
I'm also an user of Colab Pro+ and having the exact same issue.

I'm my case I use colab TPUs for running simultaneous simulations using pythons multiprocessing standard library (for my masters research). The simulations process some data and save the results in folders on my drive. They take long, so this is a process that usually runs for several hours (sometimes days for each batch).

Previously this problem didn't seem to exist and on the last sex months or so became a real issue. When I get the error again I'll try to capture the output and include it here.

**Comment by luksquaresma** [comment]
### Below follows an example of the errors happening with me:

Normal output of the code:

```
Starting error calculation
Optimization with correction =  [0.015000000000000001, 0.0657, 65.0], error = 0.2318903855723469
LR 0.9 - Step 1 - Finished adaptative optimization. last_correction_cmap = [0.015000000000000001, 0.0657, 65.0], best_correction = [0.015000000000000001, 0.0657, 65.0].
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
LR 0.5 - Starting adaptative optimization with best_correction = [0.015000000000000001, 0.0657, 65.0].
LR 0.5 - Step 0 - Current best_correction = [0.015000000000000001, 0.0657, 65.0]
LR 0.5 - Step 0 - STARTING DT = 0.001
```

Everything goes OK until here. Than the errors start when I start opening new processes for the simulation tasks:

```
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Custom TB Handler failed, unregistering
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-154faa5479d0>", line 208, in <cell line: 178>
    setup = make_setup(dt, elements, exp_field, cmap, saving_dir, log_path)
  File "<ipython-input-4-272f3c9683f5>", line 30, in make_setup
    exps_mur = get_exp_data(exp)
  File "<ipython-input-4-272f3c9683f5>", line 24, in get_exp_data
    return load_data_json(f'{os.getcwd()}/data/experimental/murayama_extremes.json')
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.10/inspect.py", line 1662, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.10/inspect.py", line 1620, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.10/inspect.py", line 829, in getsourcefile
    module = getmodule(object, filename)
  File "/usr/lib/python3.10/inspect.py", line 861, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.10/inspect.py", line 845, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.10/posixpath.py", line 384, in abspath
    cwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-154faa5479d0>", line 208, in <cell line: 178>
    setup = make_setup(dt, elements, exp_field, cmap, saving_dir, log_path)
  File "<ipython-input-4-272f3c9683f5>", line 30, in make_setup
    exps_mur = get_exp_data(exp)
  File "<ipython-input-4-272f3c9683f5>", line 24, in get_exp_data
    return load_data_json(f'{os.getcwd()}/data/experimental/murayama_extremes.json')
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 1972, in wrapped
    stb = handler(self,etype,value,tb,tb_offset=tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/dask/base.py", line 79, in _clean_ipython_traceback
    stb = self.InteractiveTB.structured_traceback(
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1367, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1267, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1124, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 382, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()
```

The errors repeat for each open process and the code doesn't finish for some time until the session crashes.

If this thing is not fixed the pro + subscription will keep having no use to me and I'll also cancel it.

**Comment by TonojiKiobya** [comment]
Honestly I don't know why colab don't solve this issue,

**Comment by Willinus-xuan** [comment]
Same problem. I will cancel colab pro+, no meaning on this. So disapointed @colaboratory-team

**Comment by isspek** [comment]
Same issue with the colab pro. Paying a fee for a buggy system is not good for a self-funded student

**Comment by cperry-goog** [comment]
This was an ephemeral issue from Drive which they resolved a few months back, closing - please do open a bug if you see it again.

**Comment by TonojiKiobya** [comment]
I subscribed to Colab Pro+, but I am only getting about 10 hours of continuous running, not 24. Why is that?. This is clearly against what Colab promised to customers who were to subscribe to Colab Pro+
