### ISSUE TITLE
Automatic 1111 crashing when running the last cell

### ISSUE THREAD

**Issue by ClaraSanders** [googlecolab/colabtools#3661]
Error loading script: api.py
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 9, in
from modules.api import api
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in
from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: batch_hijack.py
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in
from scripts import external_code
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in
from modules.api import api
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in
from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: controlnet.py
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 19, in
from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in
from modules.api import api
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in
from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

ControlNet v1.1.150
Error loading script: external_code.py
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in
from modules.api import api
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in
from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Loading weights [f8e22a0df8] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/mrcV1_mrcV1.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(7): badhandv4, anime-style-negative-embedding, easynegative, 16-token-negative-deliberate-neg, bad-hands-5, bad_quality, bad-image-v2-39000
Model loaded in 9.9s (load weights from disk: 5.3s, create model: 0.7s, apply weights to model: 2.1s, apply half(): 1.0s, move model to device: 0.7s).
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in
webui()
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 284, in create_toprow
with gr.Row(elem_id=f"{id_part}_toprow", variant="compact"):
File "/usr/local/lib/python3.10/dist-packages/gradio/layouts.py", line 44, in init
super().init(visible=visible, elem_id=elem_id, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 274, in init
super().init(visible=visible, render=render, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 79, in init
self.render()
File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 94, in render
if isinstance(self, components.TempFileManager):
AttributeError: module 'gradio.components' has no attribute 'TempFileManager'

**Comment by EvanWiederspan** [comment]
That stack trace shows a lot of AttributeErrors on gradio, which indicates that the code is probably trying to use a different version than the one available. I would recommend trying to install a different version of gradio, or reach out to the notebook author so they can update it to use the right version

**Comment by vyquocvu** [comment]
Don't update `Use_Latest_Working_Commit = True`.
