### ISSUE TITLE
ResourceExhaustedError when I use SHAP with my CNN 

### ISSUE THREAD

**Issue by fairy0127** [googlecolab/colabtools#3761]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

I use CNN to train a photo database, and I need SHAP to explain, in the past the code worked well, but these days, it runs with ResourceExhaustedError, I referred to the pr1483, and adapted my code with the suggested solution, but this error still occurred.
**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

My code should run well to show the result.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

Here is the error message:

_---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1377     try:
-> 1378       return fn(*args)
   1379     except errors.OpError as e:

9 frames
ResourceExhaustedError: 2 root error(s) found.
  (0) RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[100,128,112,112] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node gradients_1/vgg16/block2_conv2/Relu_grad/Tile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.

	 [[Func/gradients_1/dropout/cond_grad/StatelessIf/else/_54/input/_170/_253]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.

  (1) RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[100,128,112,112] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node gradients_1/vgg16/block2_conv2/Relu_grad/Tile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.

0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

ResourceExhaustedError                    Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1395                     '\nsession_config.graph_options.rewrite_options.'
   1396                     'disable_meta_optimizer = True')
-> 1397       raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
   1398 
   1399   def _extend_graph(self):

ResourceExhaustedError: Graph execution error:

Detected at node 'gradients_1/vgg16/block2_conv2/Relu_grad/Tile' defined at (most recent call last):
    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance
      app.start()
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
      self._run_once()
    File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
      handle._run()
    File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>
      lambda f: self._run_callback(functools.partial(callback, future))
    File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner
      self.ctx_run(self.run)
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request
      self.do_execute(
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
      result = self._run_cell(
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-23-e184c1303aa0>", line 6, in <cell line: 5>
      shap_values = explainer.shap_values(right_test[[i]])
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/__init__.py", line 124, in shap_values
      return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 312, in shap_values
      sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 238, in phi_symbolic
      self.phi_symbolics[i] = self.execute_with_overridden_gradients(anon)
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 408, in execute_with_overridden_gradients
      out = f()
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 236, in anon
      return tf.gradients(out, self.model_inputs)
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 378, in custom_grad
      out = op_handlers[type_name](self, op, *grads) # we cut off the shap_ prefex before the lookup
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 588, in handler
      return nonlinearity_1d_handler(input_ind, explainer, op, *grads)
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 613, in nonlinearity_1d_handler
      tf.tile(tf.abs(delta_in0), dup0) < 1e-6,
Node: 'gradients_1/vgg16/block2_conv2/Relu_grad/Tile'
Detected at node 'gradients_1/vgg16/block2_conv2/Relu_grad/Tile' defined at (most recent call last):
    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance
      app.start()
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
      self._run_once()
    File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
      handle._run()
    File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>
      lambda f: self._run_callback(functools.partial(callback, future))
    File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner
      self.ctx_run(self.run)
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request
      self.do_execute(
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
      result = self._run_cell(
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-23-e184c1303aa0>", line 6, in <cell line: 5>
      shap_values = explainer.shap_values(right_test[[i]])
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/__init__.py", line 124, in shap_values
      return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 312, in shap_values
      sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 238, in phi_symbolic
      self.phi_symbolics[i] = self.execute_with_overridden_gradients(anon)
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 408, in execute_with_overridden_gradients
      out = f()
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 236, in anon
      return tf.gradients(out, self.model_inputs)
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 378, in custom_grad
      out = op_handlers[type_name](self, op, *grads) # we cut off the shap_ prefex before the lookup
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 588, in handler
      return nonlinearity_1d_handler(input_ind, explainer, op, *grads)
    File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 613, in nonlinearity_1d_handler
      tf.tile(tf.abs(delta_in0), dup0) < 1e-6,
Node: 'gradients_1/vgg16/block2_conv2/Relu_grad/Tile'
2 root error(s) found.
  (0) RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[100,128,112,112] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node gradients_1/vgg16/block2_conv2/Relu_grad/Tile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.

	 [[Func/gradients_1/dropout/cond_grad/StatelessIf/else/_54/input/_170/_253]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.

  (1) RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[100,128,112,112] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node gradients_1/vgg16/block2_conv2/Relu_grad/Tile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.

0 successful operations.
0 derived errors ignored.

Original stack trace for 'gradients_1/vgg16/block2_conv2/Relu_grad/Tile':
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner
    self.ctx_run(self.run)
  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request
    self.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-e184c1303aa0>", line 6, in <cell line: 5>
    shap_values = explainer.shap_values(right_test[[i]])
  File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/__init__.py", line 124, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
  File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 312, in shap_values
    sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
  File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 238, in phi_symbolic
    self.phi_symbolics[i] = self.execute_with_overridden_gradients(anon)
  File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 408, in execute_with_overridden_gradients
    out = f()
  File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 236, in anon
    return tf.gradients(out, self.model_inputs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gradients_impl.py", line 311, in gradients_v2
    return gradients_util._GradientsHelper(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gradients_util.py", line 695, in _GradientsHelper
    in_grads = _MaybeCompile(grad_scope, op, func_call,
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gradients_util.py", line 329, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gradients_util.py", line 696, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 378, in custom_grad
    out = op_handlers[type_name](self, op, *grads) # we cut off the shap_ prefex before the lookup
  File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 588, in handler
    return nonlinearity_1d_handler(input_ind, explainer, op, *grads)
  File "/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.py", line 613, in nonlinearity_1d_handler
    tf.tile(tf.abs(delta_in0), dup0) < 1e-6,
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 11783, in tile
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/op_def_library.py", line 795, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 3814, in _create_op_internal
    ret = Operation(

...which was originally created as op 'vgg16/block2_conv2/Relu', defined at:
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
[elided 25 identical lines from previous traceback]
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-6faa4e7853ab>", line 34, in <cell line: 34>
    model.add(vgg16)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/trackable/base.py", line 205, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/sequential.py", line 221, in add
    layer(x)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/training.py", line 558, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/base_layer_v1.py", line 838, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/functional.py", line 512, in call
    return self._run_internal_graph(inputs, training=training, mask=mask)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/functional.py", line 669, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/base_layer_v1.py", line 838, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/layers/convolutional/base_conv.py", line 321, in call
    return self.activation(outputs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/dispatch.py", line 1176, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/activations.py", line 317, in relu
    return backend.relu(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/dispatch.py", line 1176, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)_

**Comment by fairy0127** [comment]
I have tested the same code in CPU, it works, in TPU it works, only in GPU,
it does not work.
Let me get a clean one for you later on.
Thank you so much!
Have a nice day!
Shelly
