### ISSUE TITLE
Can't add new notebook or load notebook from drive google colab

### ISSUE THREAD

**Issue by jadisayang** [googlecolab/colabtools#3775]
I have an issue with my google colab. I can't make a new notebook or load the other notebooks from my drive. 

Error
Unable to load Colaboratory.
A network error occurred and the request could not be completed.
GapiError: A network error occurred and the request could not be completed.
    at BG.zC [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/8c72f9237abda059c2d76387994229e9/external_polymer_binary.js:1556:2482)
    at new BG (https://ssl.gstatic.com/colaboratory-static/common/8c72f9237abda059c2d76387994229e9/external_polymer_binary.js:2002:424)
    at VGa (https://ssl.gstatic.com/colaboratory-static/common/8c72f9237abda059c2d76387994229e9/external_polymer_binary.js:2140:224)
    at ta.program_ (https://ssl.gstatic.com/colaboratory-static/common/8c72f9237abda059c2d76387994229e9/external_polymer_binary.js:2154:389)
    at wa (https://ssl.gstatic.com/colaboratory-static/common/8c72f9237abda059c2d76387994229e9/external_polymer_binary.js:21:57)
    at ta.throw_ (https://ssl.gstatic.com/colaboratory-static/common/8c72f9237abda059c2d76387994229e9/external_polymer_binary.js:20:201)
    at laa.throw (https://ssl.gstatic.com/colaboratory-static/common/8c72f9237abda059c2d76387994229e9/external_polymer_binary.js:22:90)
    at c (https://ssl.gstatic.com/colaboratory-static/common/8c72f9237abda059c2d76387994229e9/external_polymer_binary.js:22:345)

Someone told me if the problem is my firewall. Please help me to solve this problem.

**Comment by prajwalgangawane** [comment]
Try turning off your Access-Control-All-Origin on your chrome extension for Allow CORS

**Comment by FernandoFelipeoficial** [comment]
I'm experiencing the same problem...
When creating a new notebook, or even saving a copy to my Drive, this ERROR occurs

**Comment by jadisayang** [comment]
yes, it still happen when i turn off all my extensions but it work normally from another device

**Comment by jadisayang** [comment]
in incognito mode too

**Comment by jadisayang** [comment]
Hi guys, new updated, I've found a solution, check out this video, i clear my sll, delete the hosts and my colab work normally. 

https://www.youtube.com/watch?v=Jv48sQMotrE&t=489s&ab_channel=HostingerAcademy
