### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marcomarao2** [googlecolab/colabtools#3857]
This is what appears to me everytime I try to load any audio:

Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/EasierGUI.py", line 158, in vc_single
    load_hubert()
  File "/content/Retrieval-based-Voice-Conversion-WebUI/EasierGUI.py", line 100, in load_hubert
    models, _, _ = checkpoint_utils.load_model_ensemble_and_task(
  File "/usr/local/lib/python3.10/dist-packages/fairseq/checkpoint_utils.py", line 423, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: hubert_base.pt

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes

**Comment by cperry-goog** [comment]
I don't think this is a Colab issue - you'll want to contact the notebook author, or if that's you, share us a very minimal reproducible notebook in a new bug.
