### ISSUE TITLE
Failed to execute cell. Could not send execute message to runtime: FetchError: Could not fetch resource at https://colab.research.google.com/tun/m/gpu-a100-s-3nmtom4t6bn03/api/sessions?backend_version=next&authuser=0: 404

### ISSUE THREAD

**Issue by servasadolph** [googlecolab/colabtools#4060]
I found this error when, I run my code in Google Collab

Could not fetch resource at https://colab.research.google.com/tun/m/gpu-a100-s-3nmtom4t6bn03/api/sessions?backend_version=next&authuser=0: 404  
FetchError: Could not fetch resource at https://colab.research.google.com/tun/m/gpu-a100-s-3nmtom4t6bn03/api/sessions?backend_version=next&authuser=0: 404  
    at TG.eD [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/d0dcf2b0d7688d70bcccd1de74261a1b/external_polymer_binary.js:1639:2511)
    at new TG (https://ssl.gstatic.com/colaboratory-static/common/d0dcf2b0d7688d70bcccd1de74261a1b/external_polymer_binary.js:2067:186)
    at ra.program_ (https://ssl.gstatic.com/colaboratory-static/common/d0dcf2b0d7688d70bcccd1de74261a1b/external_polymer_binary.js:7063:681)
    at ta (https://ssl.gstatic.com/colaboratory-static/common/d0dcf2b0d7688d70bcccd1de74261a1b/external_polymer_binary.js:16:57)
    at ra.next_ (https://ssl.gstatic.com/colaboratory-static/common/d0dcf2b0d7688d70bcccd1de74261a1b/external_polymer_binary.js:14:195)
    at laa.next (https://ssl.gstatic.com/colaboratory-static/common/d0dcf2b0d7688d70bcccd1de74261a1b/external_polymer_binary.js:17:48)
    at b (https://ssl.gstatic.com/colaboratory-static/common/d0dcf2b0d7688d70bcccd1de74261a1b/external_polymer_binary.js:17:309)

**Comment by cperry-goog** [comment]
We'll need a minimal reproducible notebook to investigate
