### ISSUE TITLE
Attempting to deserialize object on CUDA device

### ISSUE THREAD

**Issue by FelixPQ** [googlecolab/colabtools#4163]
<--
I have no idea if it's a real bug or my newbieness with all this, but it seem to fail outside the Baid code.

-->

**Describe the current behavior**
I'm trying to run 
!python /content/drive/MyDrive/BAID/test.py --device 'gpu' --checkpoint_dir '/content/drive/MyDrive/BAID/checkpoint/BAID' --save_dir '/content/drive/MyDrive/BAID/result'

as shown in the readme.md file from https://github.com/Dreemurr-T/BAID.git
and I get this.

100% 3200/3200 [00:00<00:00, 311114.09it/s]
Traceback (most recent call last):
  File "/content/drive/MyDrive/BAID/test.py", line 78, in <module>
    test(args)
  File "/content/drive/MyDrive/BAID/test.py", line 39, in test
    model = SAAN(num_classes=1)
  File "/content/drive/MyDrive/BAID/models/model.py", line 101, in __init__
    self.GenAes = GAB()
  File "/content/drive/MyDrive/BAID/models/model.py", line 79, in __init__
    self._init_weights()
  File "/content/drive/MyDrive/BAID/models/model.py", line 94, in _init_weights
    self.model.load_state_dict(torch.load('/content/drive/MyDrive/BAID/epoch_99.pth'),
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1422, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1392, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1366, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 381, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 274, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 265, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

**Describe the expected behavior**
No idea of what exactly should happen

**What web browser you are using**
Chrome

**Additional context**

https://colab.research.google.com/drive/14I9t4OU5-Ra8prMr1lmSqt50IEhVCePV?usp=sharing

**Comment by cperry-goog** [comment]
You got this code from another author right? Is it possible to contact them to figure out if they have bugs?

**Comment by cperry-goog** [comment]
Yeah, if it's torch's bug I can't do anything?
