### ISSUE TITLE
error while creating a new notebook or saving a notebook to drive

### ISSUE THREAD

**Issue by kiranrag** [googlecolab/colabtools#4169]
**Describe the current behavior**
When I open google colab, welcome page with sample notebook is getting loaded and I'm able to execute that as well.
But when I create a new notebook. Getting below error. Also I'm getting same error when I try to save a copy of notebook to drive.
A network error occurred and the request could not be completed.
GapiError: A network error occurred and the request could not be completed.
    at dJ.BD [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/27ed55654157d4fccaba00d81cbe557a/external_polymer_binary.js:1642:2595)
    at new dJ (https://ssl.gstatic.com/colaboratory-static/common/27ed55654157d4fccaba00d81cbe557a/external_polymer_binary.js:2133:221)
    at XJa (https://ssl.gstatic.com/colaboratory-static/common/27ed55654157d4fccaba00d81cbe557a/external_polymer_binary.js:2237:220)
    at sa.program_ (https://ssl.gstatic.com/colaboratory-static/common/27ed55654157d4fccaba00d81cbe557a/external_polymer_binary.js:2251:383)
    at wa (https://ssl.gstatic.com/colaboratory-static/common/27ed55654157d4fccaba00d81cbe557a/external_polymer_binary.js:16:57)
    at sa.throw_ (https://ssl.gstatic.com/colaboratory-static/common/27ed55654157d4fccaba00d81cbe557a/external_polymer_binary.js:15:201)
    at laa.throw (https://ssl.gstatic.com/colaboratory-static/common/27ed55654157d4fccaba00d81cbe557a/external_polymer_binary.js:17:90)
    at c (https://ssl.gstatic.com/colaboratory-static/common/27ed55654157d4fccaba00d81cbe557a/external_polymer_binary.js:17:345)

**What web browser you are using**
Tried with chrome, firefox

**Comment by cperry-goog** [comment]
We're not sure how to debug this - can you submit feedback in product? The logs might give us a clue as to what's going on; we've never seen this. Best guess is your traffic is getting blocked by some intermediate service (your domain admin?)

**Comment by kirisakow** [comment]
I am experiencing very similar response (and failure to save) as I am trying to access my personal Colab notebooks from a corporate network behind a proxy:
```
A network error occurred and the request could not be completed.
GapiError: A network error occurred and the request could not be completed.
    at pN.KG [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/16072945715e2f0a5cb0d85e8ab66893/external_binary_l10n__fr.js:1577:5613)
    at new pN (https://ssl.gstatic.com/colaboratory-static/common/16072945715e2f0a5cb0d85e8ab66893/external_binary_l10n__fr.js:2288:221)
    at zVa (https://ssl.gstatic.com/colaboratory-static/common/16072945715e2f0a5cb0d85e8ab66893/external_binary_l10n__fr.js:2397:220)
    at va.program_ (https://ssl.gstatic.com/colaboratory-static/common/16072945715e2f0a5cb0d85e8ab66893/external_binary_l10n__fr.js:2412:387)
    at ya (https://ssl.gstatic.com/colaboratory-static/common/16072945715e2f0a5cb0d85e8ab66893/external_binary_l10n__fr.js:16:57)
    at va.throw_ (https://ssl.gstatic.com/colaboratory-static/common/16072945715e2f0a5cb0d85e8ab66893/external_binary_l10n__fr.js:15:201)
    at kaa.throw (https://ssl.gstatic.com/colaboratory-static/common/16072945715e2f0a5cb0d85e8ab66893/external_binary_l10n__fr.js:17:90)
    at c (https://ssl.gstatic.com/colaboratory-static/common/16072945715e2f0a5cb0d85e8ab66893/external_binary_l10n__fr.js:17:345)
```
