### ISSUE TITLE
chromedriver error(Compatibility Issues X)

### ISSUE THREAD

**Issue by ikko030** [googlecolab/colabtools#4247]
I have ensured compatibility between ChromeDriver and the browser, and I have also installed the latest version of Selenium. However, the code does not execute in Colab, while it does work in Jupyter Notebook.
---------------------------------------------------------------------------------------------------------------------------------------------------
from selenium import webdriver
import time

driver = webdriver.Chrome()

driver.get("https://google.com")

time.sleep(5)
---------------------------------------------------------------------------------------------------------------------------------------------------
If you run the above code, the following error occurs.
---------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------
SessionNotCreatedException                Traceback (most recent call last)
[<ipython-input-17-00d85f8dd60d>](https://localhost:8080/#) in <cell line: 4>()
      2 import time
      3 
----> 4 driver = webdriver.Chrome()
      5 
      6 driver.get("https://google.com/")

5 frames
[/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py](https://localhost:8080/#) in check_response(self, response)
    227                 alert_text = value["alert"].get("text")
    228             raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
--> 229         raise exception_class(message, screen, stacktrace)

SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /root/.cache/selenium/chrome/linux64/120.0.6099.109/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5ab48153df83 <unknown>
#1 0x5ab4811f6cf7 <unknown>
#2 0x5ab48122e60e <unknown>
#3 0x5ab48122b26e <unknown>
#4 0x5ab48127b80c <unknown>
#5 0x5ab48126fe53 <unknown>
#6 0x5ab481237dd4 <unknown>
#7 0x5ab4812391de <unknown>
#8 0x5ab481502531 <unknown>
#9 0x5ab481506455 <unknown>
#10 0x5ab4814eef55 <unknown>
#11 0x5ab4815070ef <unknown>
#12 0x5ab4814d299f <unknown>
#13 0x5ab48152b008 <unknown>
#14 0x5ab48152b1d7 <unknown>
#15 0x5ab48153d124 <unknown>
#16 0x798d53a89ac3 <unknown>
-----------------------------------------------------------------------
I just want to do web scraping...( ´༎ຶㅂ༎ຶ`)

**Comment by cperry-goog** [comment]
tracking internally at b/317372927

**Comment by Guo-SY** [comment]
I am having the same problem, if you have a solution. Please feel free to share it here. Thanks in advance!

**Comment by Amazingstar0306** [comment]
I am having the same problem too. I hope that everyone who knows about the solution let me know it

**Comment by volosied** [comment]
Same here w/ 120.0.6099.109: 
```
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-169-generic', java.version: '11.0.21'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, browserVersion: 100, chromeDriverVersion: , goog:chromeOptions: {args: [--headless], extensions: []}, platformName: ANY}], desiredCapabilities=Capabilities {browserName: chrome, browserVersion: 100, chromeDriverVersion: , goog:chromeOptions: {args: [--headless], extensions: []}, platformName: ANY}}]
	at org.jboss.arquillian.drone.webdriver.factory.SecurityActions.newInstance(SecurityActions.java:166)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.createInstance(ChromeDriverFactory.java:81)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.createInstance(ChromeDriverFactory.java:42)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:127)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:38)
	at org.jboss.arquillian.drone.impl.DroneConfigurator$1.createInstance(DroneConfigurator.java:112)
	at org.jboss.arquillian.drone.impl.CachingCallableImpl.call(CachingCallableImpl.java:44)
	at org.jboss.arquillian.core.impl.threading.ThreadedExecutorService$ContextualCallable.call(ThreadedExecutorService.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
  ```
 ``` 
 user@server:~/opensource/myfaces/integration-tests# /usr/bin/google-chrome -version
Google Chrome for Testing 120.0.6099.109 
user@server:~/opensource/myfaces/integration-tests# /usr/bin/chromedriver -version
ChromeDriver 120.0.6099.109 (3419140ab665596f21b385ce136419fde0924272-refs/branch-heads/6099@{#1483})
root@myfacesServer1:~/opensource/myfaces/integration-tests
```

I'm not sure how to debug this further :/

**Comment by alvarolgn** [comment]
Same problem, two debugging days with no results  😢

**Comment by Amazingstar0306** [comment]
Pease try to remove  the headless option!

**Comment by matthewshawnkehoe** [comment]
I have the same problem.
