### ISSUE TITLE
Downloading openssl from https://www.openssl.org/source/openssl-1.1.1m.tar.gz  Download failed: HTTP Error 404: Not Found;

### ISSUE THREAD

**Issue by Denis5555** [googlecolab/colabtools#4321]
**Describe the current behavior**
Unable to go further with Google Colab to create a Kivy apk due to error:
Downloading openssl from https://www.openssl.org/source/openssl-1.1.1m.tar.gz  
Download failed: HTTP Error 404: Not Found;

**Describe the expected behavior**
Should be able to find the page:
https://www.openssl.org/source/openssl-1.1.1m.tar.gz

**What web browser you are using**
(Chrome)

**Additional context**
[INFO]:    Downloading openssl
[INFO]:    -> directory context /content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/packages/openssl
[DEBUG]:   -> running basename https://www.openssl.org/source/openssl-1.1.1m.tar.gz
[DEBUG]:   	openssl-1.1.1m.tar.gz
[DEBUG]:   Downloading openssl from https://www.openssl.org/source/openssl-1.1.1m.tar.gz
[DEBUG]:   -> running rm -f .mark-openssl-1.1.1m.tar.gz
[INFO]:    Downloading openssl from https://www.openssl.org/source/openssl-1.1.1m.tar.gz
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1262, in <module>
    main()
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 680, in __init__
    getattr(self, command)(args)
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 99, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 158, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 482, in build_recipes
    recipe.download_if_necessary()
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 349, in download_if_necessary
    self.download()
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 399, in download
    self.download_file(self.versioned_url, filename)
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 203, in download_file
    urlretrieve(url, target, report_hook)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Download failed: HTTP Error 404: Not Found; retrying in 1 second(s)...Download failed: HTTP Error 404: Not Found; retrying in 2 second(s)...Download failed: HTTP Error 404: Not Found; retrying in 4 second(s)...Download failed: HTTP Error 404: Not Found; retrying in 8 second(s)...# Command failed: ['/usr/bin/python3', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=verbfr', '--bootstrap=sdl2', '--requirements=python3,kivy,kivymd,pillow,verbecc,iniconfig,joblib,lxml,lxml-stubs,packaging,pluggy,pytest,threadpoolctl,Cython,mlconjug,scikit-learn,certifi,chardet,idna,requests,scikit-learn,urllib3', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']

**Comment by mayankmalik-colab** [comment]
This is definitely not Colab issue. It's a known openssl issue - https://github.com/openssl/web/issues/453 . As per the comments there, it should have been fixed though.
