### ISSUE TITLE
Notebook upload not working in Chrome

### ISSUE THREAD

**Issue by gaborxfabian** [googlecolab/colabtools#4328]
**Describe the current behavior**
Re-uploading any notebook previously downloaded from Colab fails.

Message:
Cannot read properties of undefined (reading 'files')
TypeError: Cannot read properties of undefined (reading 'files')
    at a (https://ssl.gstatic.com/colaboratory-static/common/f6c736cbde16632a9fcd16d9ab1970b1/external_polymer_binary.js:2392:156)
    at ua.program_ (https://ssl.gstatic.com/colaboratory-static/common/f6c736cbde16632a9fcd16d9ab1970b1/external_polymer_binary.js:2256:1)
    at wa (https://ssl.gstatic.com/colaboratory-static/common/f6c736cbde16632a9fcd16d9ab1970b1/external_polymer_binary.js:16:57)
    at ua.next_ (https://ssl.gstatic.com/colaboratory-static/common/f6c736cbde16632a9fcd16d9ab1970b1/external_polymer_binary.js:14:195)
    at laa.next (https://ssl.gstatic.com/colaboratory-static/common/f6c736cbde16632a9fcd16d9ab1970b1/external_polymer_binary.js:17:48)
    at https://ssl.gstatic.com/colaboratory-static/common/f6c736cbde16632a9fcd16d9ab1970b1/external_polymer_binary.js:17:463
    at new Promise (<anonymous>)
    at maa (https://ssl.gstatic.com/colaboratory-static/common/f6c736cbde16632a9fcd16d9ab1970b1/external_polymer_binary.js:17:356)
    at z (https://ssl.gstatic.com/colaboratory-static/common/f6c736cbde16632a9fcd16d9ab1970b1/external_polymer_binary.js:18:22)
    at https://ssl.gstatic.com/colaboratory-static/common/f6c736cbde16632a9fcd16d9ab1970b1/external_polymer_binary.js:2255:417

**Describe the expected behavior**
I expect to be able to upload previously downloaded noteboks

**What web browser you are using**
Google Chrome

**Additional context**
My account has Google Drive disabled due to company policy as I am using a corporate account (MSCI). I get the error when trying to upload any notebook downloaded from Colab, even the Welcome to Colab notebook.

**Comment by EvanWiederspan** [comment]
Uploading a notebook saves the notebook to your Drive, so I wouldn't expect uploading to work if your Drive access is disabled
