### ISSUE TITLE
I can't cancel my google colab subscription

### ISSUE THREAD

**Issue by PuTaTus** [googlecolab/colabtools#4355]
When i try to cancel via https://colab.research.google.com/cancel-subscription?authuser=1, it produces this.

Subscription is not in a state that allows cancellation

Could not fetch resource at https://colab.research.google.com/subscriptions/cancel?authuser=1: 400  
Gb@https://ssl.gstatic.com/colaboratory-static/common/ac0f656b1dd1353463e3dd69fc520cdd/subscriptions_cancel_binary.js:65:460
XN@https://ssl.gstatic.com/colaboratory-static/common/ac0f656b1dd1353463e3dd69fc520cdd/subscriptions_cancel_binary.js:802:829
$N@https://ssl.gstatic.com/colaboratory-static/common/ac0f656b1dd1353463e3dd69fc520cdd/subscriptions_cancel_binary.js:802:1120
p7/<@https://ssl.gstatic.com/colaboratory-static/common/ac0f656b1dd1353463e3dd69fc520cdd/subscriptions_cancel_binary.js:2009:176
Ea@https://ssl.gstatic.com/colaboratory-static/common/ac0f656b1dd1353463e3dd69fc520cdd/subscriptions_cancel_binary.js:13:42
Ca.prototype.jy@https://ssl.gstatic.com/colaboratory-static/common/ac0f656b1dd1353463e3dd69fc520cdd/subscriptions_cancel_binary.js:11:304
Ga/this.next@https://ssl.gstatic.com/colaboratory-static/common/ac0f656b1dd1353463e3dd69fc520cdd/subscriptions_cancel_binary.js:13:304
b@https://ssl.gstatic.com/colaboratory-static/common/ac0f656b1dd1353463e3dd69fc520cdd/subscriptions_cancel_binary.js:14:127

**Comment by katlyn-edwards** [comment]
Hrmm, can you file in app feedback so we can look into this more? Please reference this github issue. 

Usually we see this if your account is in a bad state - like your payment method is incorrect, and it wasn't able to renew.

**Comment by zisismp4** [comment]
Hi, I am getting the same error.

Could not fetch resource at https://colab.research.google.com/subscriptions/cancel?authuser=0: 400  
FetchError: Could not fetch resource at https://colab.research.google.com/subscriptions/cancel?authuser=0: 400  
    at $N.XN [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/f9d73783954cf93a17feb9636958b622/subscriptions_cancel_binary_l10n__el.js:809:945)
    at new $N (https://ssl.gstatic.com/colaboratory-static/common/f9d73783954cf93a17feb9636958b622/subscriptions_cancel_binary_l10n__el.js:809:1236)
    at Da.ca (https://ssl.gstatic.com/colaboratory-static/common/f9d73783954cf93a17feb9636958b622/subscriptions_cancel_binary_l10n__el.js:2114:84)
    at Fa (https://ssl.gstatic.com/colaboratory-static/common/f9d73783954cf93a17feb9636958b622/subscriptions_cancel_binary_l10n__el.js:13:42)
    at Da.gz (https://ssl.gstatic.com/colaboratory-static/common/f9d73783954cf93a17feb9636958b622/subscriptions_cancel_binary_l10n__el.js:11:304)
    at Ha.next (https://ssl.gstatic.com/colaboratory-static/common/f9d73783954cf93a17feb9636958b622/subscriptions_cancel_binary_l10n__el.js:13:304)
    at b (https://ssl.gstatic.com/colaboratory-static/common/f9d73783954cf93a17feb9636958b622/subscriptions_cancel_binary_l10n__el.js:14:127)
    
    Any updates?

**Comment by katlyn-edwards** [comment]
The last update from me explains this issue - it's intentional, we aren't able to cancel subscriptions where the form of payment is invalid or if it failed to renew.

**Comment by Jumanh12** [comment]
I'm getting the same issue, could you tell me how you resolved it?

**Comment by katlyn-edwards** [comment]
We aren't able to diagnose billing issues over GitHub, please email [colab-billing@google.com](mailto:colab-billing@google.com)

**Comment by samarskii** [comment]
The same problem here, and writing to [colab-billing@google.com](mailto:colab-billing@google.com) doesn't help. 

So I am changing my credit card in the bank for a new one and in the future not going to do any business with google or their products.

**Comment by khpankiv** [comment]
The same for me. And please, don't talk about bad payment methods, because it take money from my card with no problem

**Comment by Ashlalala** [comment]
Fokk google and google colab

**Comment by arndri** [comment]
Why is it so hard for people to cancel subscription, u want money from us so bad ?

**Comment by cperry-goog** [comment]
If you visit https://colab.research.google.com/cancel-subscription you can cancel any subscription you have. Or email us, or submit feedback in product. We have many ways to cancel!

**Comment by katlyn-edwards** [comment]
You can also visit payments.google.com click on "Subscriptions and Services" and cancel from there.

**Comment by ostratonov** [comment]
same issue for me, uncancellable state, colab support does not answer

**Comment by katlyn-edwards** [comment]
Can you include any information on why it's "uncancellable"? Is there something on the payments website that makes you think you can't cancel it? Payments is the source-of-truth for Colab, so if you can't cancel it there, then you should reach out to Google Payments.

**Comment by LeonRonchi** [comment]
Same here, i cant cancel, no cancel button. Has anyone managed to cancel?

**Comment by Ahmad-Th** [comment]
I had the same issue, and tried many solutions, none has worked, except for closing the whole payment profile, as explained below:

https://support.google.com/googlepay/answer/7643930?hl=en#:~:text=Optional%3A%20If%20you%20have%20multiple,%2C%E2%80%9D%20select%20Close%20payments%20profile.

Hopefully the will work for you as well

**Comment by mttariqi** [comment]
They bloody neither lets cancel nor there is any other way to cancel 
Could not fetch resource at https://colab.research.google.com/subscriptions/cancel?authuser=0: 400  
FetchError: Could not fetch resource at https://colab.research.google.com/subscriptions/cancel?authuser=0: 400  
    at tS.rS [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/d174e787cb0f4230f2c9f8dfd7cdf663/subscriptions_cancel_binary.js:704:681)
    at new tS (https://ssl.gstatic.com/colaboratory-static/common/d174e787cb0f4230f2c9f8dfd7cdf663/subscriptions_cancel_binary.js:704:918)
    at Ia.B (https://ssl.gstatic.com/colaboratory-static/common/d174e787cb0f4230f2c9f8dfd7cdf663/subscriptions_cancel_binary.js:1814:167)
    at La (https://ssl.gstatic.com/colaboratory-static/common/d174e787cb0f4230f2c9f8dfd7cdf663/subscriptions_cancel_binary.js:12:40)
    at Ma.next (https://ssl.gstatic.com/colaboratory-static/common/d174e787cb0f4230f2c9f8dfd7cdf663/subscriptions_cancel_binary.js:13:91)
    at b (https://ssl.gstatic.com/colaboratory-static/common/d174e787cb0f4230f2c9f8dfd7cdf663/subscriptions_cancel_binary.js:14:39)

**Comment by rye0x** [comment]
Same issue with me!

Could not fetch resource at https://colab.research.google.com/subscriptions/cancel?authuser=0: 400  
FetchError: Could not fetch resource at https://colab.research.google.com/subscriptions/cancel?authuser=0: 400  
    at HS.FS [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/d48bf56c2e6b7de5c11b869b6ba36dba/subscriptions_cancel_binary.js:710:366)  
    at new HS (https://ssl.gstatic.com/colaboratory-static/common/d48bf56c2e6b7de5c11b869b6ba36dba/subscriptions_cancel_binary.js:710:603)  
    at Ja.B (https://ssl.gstatic.com/colaboratory-static/common/d48bf56c2e6b7de5c11b869b6ba36dba/subscriptions_cancel_binary.js:1827:167)  
    at Ma (https://ssl.gstatic.com/colaboratory-static/common/d48bf56c2e6b7de5c11b869b6ba36dba/subscriptions_cancel_binary.js:12:40)  
    at Na.next (https://ssl.gstatic.com/colaboratory-static/common/d48bf56c2e6b7de5c11b869b6ba36dba/subscriptions_cancel_binary.js:13:91)  
    at b (https://ssl.gstatic.com/colaboratory-static/common/d48bf56c2e6b7de5c11b869b6ba36dba/subscriptions_cancel_binary.js:14:39)

**Comment by amichae2** [comment]
Dark patterns, the people who work at this company should be ashamed that they, themselves exist.
