### ISSUE TITLE
Frame processor face_enhancer not found

### ISSUE THREAD

**Issue by Ferbeca1972** [googlecolab/colabtools#4373]
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Frame processor face_enhancer not found

**Comment by cperry-goog** [comment]
We'll need a minimal reproducible notebook to investigate.

**Comment by Ferbeca1972** [comment]
Agora esta dando este erro: 
Traceback (most recent call last):
  File "/content/roop/run.py", line 3, in <module>
    from roop import core
  File "/content/roop/roop/core.py", line 20, in <module>
    import roop.ui as ui
  File "/content/roop/roop/ui.py", line 15, in <module>
    from roop.predictor import predict_frame, clear_predictor
  File "/content/roop/roop/predictor.py", line 3, in <module>
    import opennsfw2
  File "/usr/local/lib/python3.10/dist-packages/opennsfw2/__init__.py", line 4, in <module>
    from ._inference import Aggregation
  File "/usr/local/lib/python3.10/dist-packages/opennsfw2/_inference.py", line 16, in <module>
    from ._model import make_open_nsfw_model
  File "/usr/local/lib/python3.10/dist-packages/opennsfw2/_model.py", line 12, in <module>
    from tensorflow.keras import layers  # type: ignore # pylint: disable=import-error
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__init__.py", line 3, in <module>
    from keras.api._v2.keras import __internal__
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__init__.py", line 3, in <module>
    from keras.api._v2.keras import __internal__
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__internal__/__init__.py", line 3, in <module>
    from keras.api._v2.keras.__internal__ import backend
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__internal__/backend/__init__.py", line 3, in <module>
    from keras.src.backend import _initialize_variables as initialize_variables
ImportError: cannot import name '_initialize_variables' from 'keras.src.backend' (/usr/local/lib/python3.10/dist-packages/keras/src/backend/__init__.py)

**Comment by Ferbeca1972** [comment]
Gostaria de saber o que deve fazer, se não terei que cancelar a assinatura

**Comment by EvanWiederspan** [comment]
We cannot help without a notebook that shows the code you are running and the error you are seeing
