### ISSUE TITLE
Erro na geração do deepfake: Traceback (most recent call last):

### ISSUE THREAD

**Issue by Ferbeca1972** [googlecolab/colabtools#4378]
Erro na geração final do deepfake:

Traceback (most recent call last):
  File "/content/roop/roop/roop/run.py", line 3, in <module>
    from roop import core
  File "/content/roop/roop/roop/roop/core.py", line 20, in <module>
    import roop.ui as ui
  File "/content/roop/roop/roop/roop/ui.py", line 15, in <module>
    from roop.predictor import predict_frame, clear_predictor
  File "/content/roop/roop/roop/roop/predictor.py", line 3, in <module>
    import opennsfw2
  File "/usr/local/lib/python3.10/dist-packages/opennsfw2/__init__.py", line 4, in <module>
    from ._inference import Aggregation
  File "/usr/local/lib/python3.10/dist-packages/opennsfw2/_inference.py", line 16, in <module>
    from ._model import make_open_nsfw_model
  File "/usr/local/lib/python3.10/dist-packages/opennsfw2/_model.py", line 12, in <module>
    from tensorflow.keras import layers  # type: ignore # pylint: disable=import-error
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__init__.py", line 3, in <module>
    from keras.api._v2.keras import __internal__
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__init__.py", line 3, in <module>
    from keras.api._v2.keras import __internal__
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__internal__/__init__.py", line 3, in <module>
    from keras.api._v2.keras.__internal__ import backend
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__internal__/backend/__init__.py", line 3, in <module>
    from keras.src.backend import _initialize_variables as initialize_variables
ImportError: cannot import name '_initialize_variables' from 'keras.src.backend' (/usr/local/lib/python3.10/dist-packages/keras/src/backend/__init__.py)

**Comment by EvanWiederspan** [comment]
This looks to be the same as https://github.com/googlecolab/colabtools/issues/4381. If you have a repro notebook to share, go ahead and paste it there instead. I would recommend reaching out to the notebook author instead, though
