### ISSUE TITLE
importerror

### ISSUE THREAD

**Issue by ocptnt** [googlecolab/colabtools#4381]
Traceback (most recent call last):
  File "/content/roop/run.py", line 3, in <module>
    from roop import core
  File "/content/roop/roop/core.py", line 20, in <module>
    import roop.ui as ui
  File "/content/roop/roop/ui.py", line 15, in <module>
    from roop.predictor import predict_frame, clear_predictor
  File "/content/roop/roop/predictor.py", line 3, in <module>
    import opennsfw2
  File "/usr/local/lib/python3.10/dist-packages/opennsfw2/__init__.py", line 4, in <module>
    from ._inference import Aggregation
  File "/usr/local/lib/python3.10/dist-packages/opennsfw2/_inference.py", line 16, in <module>
    from ._model import make_open_nsfw_model
  File "/usr/local/lib/python3.10/dist-packages/opennsfw2/_model.py", line 12, in <module>
    from tensorflow.keras import layers  # type: ignore # pylint: disable=import-error
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__init__.py", line 3, in <module>
    from keras.api._v2.keras import __internal__
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__init__.py", line 3, in <module>
    from keras.api._v2.keras import __internal__
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__internal__/__init__.py", line 3, in <module>
    from keras.api._v2.keras.__internal__ import backend
  File "/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__internal__/backend/__init__.py", line 3, in <module>
    from keras.src.backend import _initialize_variables as initialize_variables
ImportError: cannot import name '_initialize_variables' from 'keras.src.backend' (/usr/local/lib/python3.10/dist-packages/keras/src/backend/__init__.py)

**Comment by EvanWiederspan** [comment]
Can you provide a repro notebook? In general, though, if you're running a notebook that you didn't create, you should reach out to the notebook author instead

**Comment by anyone1999** [comment]
I m getting this error while trying to create my own notebook
Traceback (most recent call last):
  File "/home/studio-lab-user/roop/run.py", line 3, in <module>
    from roop import core
  File "/home/studio-lab-user/roop/roop/core.py", line 20, in <module>
    import roop.ui as ui
  File "/home/studio-lab-user/roop/roop/ui.py", line 7, in <module>
    import cv2
  File "/home/studio-lab-user/.conda/envs/roop/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/studio-lab-user/.conda/envs/roop/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/studio-lab-user/.conda/envs/roop/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by cperry-goog** [comment]
Still need a minimal reproducible notebook to investigate.
