### ISSUE TITLE
Sequence Invalid Error

### ISSUE THREAD

**Issue by bregman3** [googlecolab/colabtools#4438]
When I use the colab through ChimeraX, I get an error where it tells me my sequence has an invalid character. I have tried different sequences and tried monomers and multimers and I get the same error every time. 
I didn't have this problem until like 2-3 days ago.
Here is the error:
2024-03-15 17:04:10,356 Starting prediction on 2024-03-15 UTC time
2024-03-15 17:04:10,356 Installing ColabFold on Google Colab virtual machine.
Using Tesla T4 graphics processor
2024-03-15 17:04:10,580 Running on GPU
2024-03-15 17:04:10,583 Found 5 citations for tools or databases
2024-03-15 17:04:10,583 Query 1/1: af12 (length 12)
PENDING:   0%|          | 0/150 [elapsed: 00:00 remaining: ?]2024-03-15 17:04:11,278 Sleeping for 8s. Reason: PENDING
ERROR:   0%|          | 0/150 [elapsed: 00:09 remaining: ?]2024-03-15 17:04:20,039 Could not get MSA/templates for af12: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/colabfold/batch.py", line 1483, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/usr/local/lib/python3.10/dist-packages/colabfold/batch.py", line 844, in get_msa_and_templates
    a3m_lines = run_mmseqs2(
  File "/usr/local/lib/python3.10/dist-packages/colabfold/colabfold.py", line 238, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2024-03-15 17:04:20,044 Done

I've also tried restarting the session and everything.

**Comment by cperry-goog** [comment]
I cannot diagnose this without a minimal reproducible notebook I am sorry. If you share that we can take a look, but many times the resolution is to contact the notebook author to figure out how they've designed this.
