### ISSUE TITLE
GFPGAN ERROR MESSAGE: ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor' 

### ISSUE THREAD

**Issue by bigeye-studios** [googlecolab/colabtools#4476]
I'm running Chrome Version 123.0.6312.87 (Official Build) (arm64) and on the GFPGAN site and getting the following error message on Inference.  I have TorchVision version 0.19.0.dev20240322 installed in my environment. Not sure what to do here. Thanks!

Traceback (most recent call last):
  File "/content/GFPGAN/inference_gfpgan.py", line 7, in <module>
    from basicsr.utils import imwrite
  File "/usr/local/lib/python3.10/dist-packages/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
ls: cannot access 'results/cmp': No such file or directory

**Comment by cperry-goog** [comment]
I think you'll have more luck contacting the notebook author, though I can take a look if you share a minimal reproducible notebook here.
