### ISSUE TITLE
Ubuntu 22.04 geckodriver/firefox crashes

### ISSUE THREAD

**Issue by shenmadouyaowen** [googlecolab/colabtools#4562]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
 I have reinstalled firefox according to #3861 , but still report the following error. Can you help me

```
>>> from selenium import webdriver
>>> browser = webdriver.Firefox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/dg/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/root/anaconda3/envs/dg/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "/root/anaconda3/envs/dg/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/anaconda3/envs/dg/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/root/anaconda3/envs/dg/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1


```

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by shenmadouyaowen** [comment]
Solved, cannot run as root user
