### ISSUE TITLE
Cannot open Colab notebook

### ISSUE THREAD

**Issue by Isma-collab** [googlecolab/colabtools#4694]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
Cannot open Colab notebook
**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

Error
Unable to load Colab.

A network error occurred and the request could not be completed.
GapiError: A network error occurred and the request could not be completed.
    at aN.gE [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/b805782a7d381ac4661b5fa38ade2fda/external_binary.js:1647:2813)
    at new aN (https://ssl.gstatic.com/colaboratory-static/common/b805782a7d381ac4661b5fa38ade2fda/external_binary.js:2335:221)
    at HPa (https://ssl.gstatic.com/colaboratory-static/common/b805782a7d381ac4661b5fa38ade2fda/external_binary.js:2441:220)
    at xa.program_ (https://ssl.gstatic.com/colaboratory-static/common/b805782a7d381ac4661b5fa38ade2fda/external_binary.js:2455:387)
    at Aa (https://ssl.gstatic.com/colaboratory-static/common/b805782a7d381ac4661b5fa38ade2fda/external_binary.js:16:57)
    at xa.throw_ (https://ssl.gstatic.com/colaboratory-static/common/b805782a7d381ac4661b5fa38ade2fda/external_binary.js:15:201)
    at kaa.throw (https://ssl.gstatic.com/colaboratory-static/common/b805782a7d381ac4661b5fa38ade2fda/external_binary.js:17:90)
    at c (https://ssl.gstatic.com/colaboratory-static/common/b805782a7d381ac4661b5fa38ade2fda/external_binary.js:17:345)
OK

**Comment by EvanWiederspan** [comment]
Can you share the link to the notebook you are trying to open? Also, does this repro for you in incognito mode with all browser extensions disabled?

**Comment by EvanWiederspan** [comment]
We've also seen this caused by a firewall, either on your machine or put up by your domain administrator

**Comment by Isma-collab** [comment]
> Can you share the link to the notebook you are trying to open? Also, does this repro for you in incognito mode with all browser extensions disabled?

Hi Evan:
https://colab.research.google.com/#create=true
this is the link Im using.
thank you

**Comment by cperry-goog** [comment]
Are you logged in with a workspace account? Or is this a gmail account you're trying from?

**Comment by rockyforever8-sys** [comment]
A network error occurred and the request could not be completed.
GapiError: A network error occurred and the request could not be completed.
    at rO.TG [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:1786:731)
    at new rO (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:2563:384)
    at gib (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:2670:220)
    at qa.program_ (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:2682:419)
    at ta (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:19:57)
    at qa.throw_ (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:18:202)
    at oaa.throw (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:20:90)
    at c (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:20:345)

**Comment by rockyforever8-sys** [comment]
I cant load a new notebook and the error shown below. Can you please guide me how to solve this ? Please 

A network error occurred and the request could not be completed.
GapiError: A network error occurred and the request could not be completed.
    at rO.TG [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:1786:731)
    at new rO (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:2563:384)
    at gib (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:2670:220)
    at qa.program_ (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:2682:419)
    at ta (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:19:57)
    at qa.throw_ (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:18:202)
    at oaa.throw (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:20:90)
    at c (https://ssl.gstatic.com/colaboratory-static/common/4b60dfb3f2f1377b72c39fc9ebe6604a/external_binary.js:20:345)
