### ISSUE TITLE
failed to fetch

### ISSUE THREAD

**Issue by elifbykrbc** [googlecolab/colabtools#4722]
since last day, i'm keep getting same error that says 'failed to fetch'. it'd started my ai project but now even print("hello world") is failed same way. i tried several things to fix.

**Comment by mhsalimi78** [comment]
Me too.
I hope we find a solution

**Comment by vafaeim** [comment]
I am experiencing the same issue. All commands fail to execute, returning the following error:

```
Error
Failed to execute cell. Could not send execute message to runtime: TypeError: Failed to fetch
Failed to fetch
TypeError: Failed to fetch
    at wa.program_ (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:7057:130)
    at ya (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:16:57)
    at wa.next_ (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:14:195)
    at kaa.next (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:17:48)
    at https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:17:463
    at new Promise (<anonymous>)
    at laa (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:17:356)
    at z (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:18:22)
    at k7.fetch (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:7056:76)
    at wa.program_ (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:7055:336)
```

Has anyone found a resolution or workaround for this issue? Any assistance would be greatly appreciated.

**Comment by javad-sajady** [comment]
i get the same error i don't know why and I can't run any code on my colab not even new notebooks

**Comment by cperry-goog** [comment]
Hi folks, thanks for commenting. A recent update caused an issue connecting for a small number of our users. This has now been resolved. We have not changed any geo availability of Colab. Please open a new bug if you encounter new connection issues.
