### ISSUE TITLE
No connection to runtime

### ISSUE THREAD

**Issue by huskerfly** [googlecolab/colabtools#4729]
**Describe the current behavior**
Unable to connect to runtime - any emails, different files, different computers, different browsers, cleared cache and all that good stuff. 

**Describe the expected behavior**
Shit to run properly. 

**What web browser you are using**
Brave, Chrome, Edge

**Additional context**

Failed to fetch
TypeError: Failed to fetch
    at wa.program_ (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:7057:130)
    at ya (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:16:57)
    at wa.next_ (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:14:195)
    at kaa.next (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:17:48)
    at https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:17:463
    at new Promise (<anonymous>)
    at laa (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:17:356)
    at z (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:18:22)
    at k7.fetch (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:7056:76)
    at wa.program_ (https://ssl.gstatic.com/colaboratory-static/common/c70290018adb9d32b4702b0c8818020b/external_binary.js:7055:336)

**Comment by Hamedeng64** [comment]
I have same problem, where are you from?

**Comment by huskerfly** [comment]
USA

**Comment by cperry-goog** [comment]
Hi folks, thanks for commenting. A recent update caused an issue connecting for a small number of our users. This has now been resolved. We have not changed any geo availability of Colab. Please open a new bug if you encounter new connection issues.
