### ISSUE TITLE
Colab not opening

### ISSUE THREAD

**Issue by Sakshamsinha23** [googlecolab/colabtools#4853]
A network error occurred and the request could not be completed.
GapiError: A network error occurred and the request could not be completed.
    at VN.SF [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/333325de257f4dad01c334babcb67982/external_binary.js:1564:2785)
    at new VN (https://ssl.gstatic.com/colaboratory-static/common/333325de257f4dad01c334babcb67982/external_binary.js:2254:221)
    at cSa (https://ssl.gstatic.com/colaboratory-static/common/333325de257f4dad01c334babcb67982/external_binary.js:2360:220)
    at wa.program_ (https://ssl.gstatic.com/colaboratory-static/common/333325de257f4dad01c334babcb67982/external_binary.js:2374:387)
    at ya (https://ssl.gstatic.com/colaboratory-static/common/333325de257f4dad01c334babcb67982/external_binary.js:16:57)
    at wa.throw_ (https://ssl.gstatic.com/colaboratory-static/common/333325de257f4dad01c334babcb67982/external_binary.js:15:201)
    at kaa.throw (https://ssl.gstatic.com/colaboratory-static/common/333325de257f4dad01c334babcb67982/external_binary.js:17:90)
    at c (https://ssl.gstatic.com/colaboratory-static/common/333325de257f4dad01c334babcb67982/external_binary.js:17:345)

**Comment by ria147** [comment]
Facing the same issue. Tried clearing cache, flushing dns, clearing ssl state, restarting, different browser, different network (vpn), still keep getting the same error.

**Comment by Sakshamsinha23** [comment]
No Its doesn't work I had to reset all the site settings

**Comment by katlyn-edwards** [comment]
We've heard a few reports of this, but can't repro on our side -- can someone include a HAR file showing the network activity (including the failed request?)

Here's a support article that explains how to capture a HAR file - https://support.google.com/admanager/answer/10358597?hl=en

**Comment by ria147** [comment]
I had issues with not only Google Colab, but also Google Docs and Google Slides home pages not loading. What fixed it for me was disabling all my browser extensions and then enabling one at a time till I was able to locate the one preventing the loading.
