### ISSUE TITLE
BUG in frontend: dot files.

### ISSUE THREAD

**Issue by 0wwafa** [googlecolab/colabtools#4854]
If you create a file starting with a dot, it is shown greyed in the file browser (and that's fine).
It can be renamed or deleted, and that's fine too.
But it does not load in the editor and spits out an error:
```
Could not fetch resource at https://8080-m-s-fxxxxa.us-east4-0.prod.colab.dev/files/content/.iceConfig?authuser=0&colab-runtime-proxy-token=eyJhbGciOiJFUzI1NiIsICJraWQiOiJMaxxxE5GYUEifQ.eyJhdWQiOiJtLXMtZmthcHp4NWFxxxxwgInBvcnQiOjgwODB9.Y66nuxGtRycIXTfbH3jTe-yHf7BncXHzk809VeoMBclCYPMxB1cgzuem7YGmp8BTf50sMmNtQJaiTdPEo6FnHg: 500  
FetchError: Could not fetch resource at https://8080-m-s-fkapzx5almxxxx.prod.colab.dev/files/content/.iceConfig?authuser=0&colab-runtime-proxy-token=eyJhbGciOiJFUzI1NiIsICJraWQiOiJMaE5GYUEifQ.eyJhdWQiOiJtLXMtZmthcHp4NWFsbTg5IiwgImV4cCI6MTcyNzAwMjE3NCwgInBvcnQiOjgwODB9.Y66nuxGtRycIXTfbH3jTe-yxxxoMBclCYPMxB1cgzuem7YGmp8BTf50sMmNtQJaiTdPEo6FnHg: 500  
    at cM.KE [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/f4182a9b4b18d98c6aad3bce96bb48fd/external_binary.js:1559:2785)
    at new cM (https://ssl.gstatic.com/colaboratory-static/common/f4182a9b4b18d98c6aad3bce96bb48fd/external_binary.js:2184:186)
    at wa.program_ (https://ssl.gstatic.com/colaboratory-static/common/f4182a9b4b18d98c6aad3bce96bb48fd/external_binary.js:7145:355)
    at ya (https://ssl.gstatic.com/colaboratory-static/common/f4182a9b4b18d98c6aad3bce96bb48fd/external_binary.js:16:57)
    at wa.next_ (https://ssl.gstatic.com/colaboratory-static/common/f4182a9b4b18d98c6aad3bce96bb48fd/external_binary.js:14:195)
    at kaa.next (https://ssl.gstatic.com/colaboratory-static/common/f4182a9b4b18d98c6aad3bce96bb48fd/external_binary.js:17:48)
    at b (https://ssl.gstatic.com/colaboratory-static/common/f4182a9b4b18d98c6aad3bce96bb48fd/external_binary.js:17:309)

```

**Comment by Aanshuu** [comment]
colab/cloud environment sometimes restrict server-side files to open. If you want to edit change the file name to just config removing the dot, edit it and then rename it. That's the only solution for the time being. (You can't resolve server side issue)

**Comment by cperry-goog** [comment]
This is a great find, thanks. b/371203949 to track internally

**Comment by sagelywizard** [comment]
There's a pending fix for this. Should be live later this week.

**Comment by colaboratory-team** [comment]
This is fixed now
