### ISSUE TITLE
in my window edge browser cannot Open colab notebook 

### ISSUE THREAD

**Issue by azhongai666** [googlecolab/colabtools#4916]
**What web browser you are using**
edge

today  i can  open Google  drive, but can't open  colab  notebook , it always show the below error  message. 

but in same  computer , i can do it in Chrome browser . 

i need  help, why this happen , thanks very much !

Requests from referer https://drive.google.com/drive/folders/1YCiBsH36ZeHrv5LNPRx56R1lE0bagC94 are blocked.
GapiError: Requests from referer https://drive.google.com/drive/folders/1YCiBsH36ZeHrv5LNPRx56R1lE0bagC94 are blocked.
    at NN.zG [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/f6445d5820f0bcf9eeb37a29e646106d/external_binary_l10n__zh_cn.js:1577:2785)
    at new NN (https://ssl.gstatic.com/colaboratory-static/common/f6445d5820f0bcf9eeb37a29e646106d/external_binary_l10n__zh_cn.js:2288:221)
    at rTa (https://ssl.gstatic.com/colaboratory-static/common/f6445d5820f0bcf9eeb37a29e646106d/external_binary_l10n__zh_cn.js:2396:220)
    at ua.program_ (https://ssl.gstatic.com/colaboratory-static/common/f6445d5820f0bcf9eeb37a29e646106d/external_binary_l10n__zh_cn.js:2411:387)
    at xa (https://ssl.gstatic.com/colaboratory-static/common/f6445d5820f0bcf9eeb37a29e646106d/external_binary_l10n__zh_cn.js:16:57)
    at ua.throw_ (https://ssl.gstatic.com/colaboratory-static/common/f6445d5820f0bcf9eeb37a29e646106d/external_binary_l10n__zh_cn.js:15:201)
    at kaa.throw (https://ssl.gstatic.com/colaboratory-static/common/f6445d5820f0bcf9eeb37a29e646106d/external_binary_l10n__zh_cn.js:17:90)
    at c (https://ssl.gstatic.com/colaboratory-static/common/f6445d5820f0bcf9eeb37a29e646106d/external_binary_l10n__zh_cn.js:17:345)

**Comment by cperry-goog** [comment]
Can you try this from an incognito window?

And is this a gmail account or a Workspace account? Your admin may have disabled Colab.
