### ISSUE TITLE
PyDrive causing a lot of errors when being run

### ISSUE THREAD

**Issue by nicholaswood** [googlecolab/colabtools#605]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
I'm using the PyDrive library for loading and saving files to my personal Google drive.  I import and install the following:

```!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
```
My code has commands like:
```
def auth_google():
  # Authenticate and create the PyDrive client.
  # This only needs to be done once per notebook.
  auth.authenticate_user()
  gauth = GoogleAuth()
  gauth.credentials = GoogleCredentials.get_application_default()
  drive = GoogleDrive(gauth)
  
  return drive
```

```
def list_directory(drive,dir_id):
  file_list = drive.ListFile({'q': "'"+dir_id+"' in parents and trashed=false"}).GetList()
  return file_list

def upload_file(file_name, file_dir=''):
  drive = auth_google()
  
  root_list = list_directory(drive,'root')
  
  for file in root_list:
    if file['title'] == file_name:
      upload_file = drive.CreateFile({'id': file['id']})
      print("File found")
      break
    else:
      upload_file = drive.CreateFile()

  file_path = os.path.join(file_dir,file_name)
  upload_file.SetContentFile(file_name)
  upload_file.Upload()
  dir_list = list_directory(drive,'root')

  for file in dir_list:
    if file['title'] == file_name:
      print('File Uploaded: '+file_name)
```

As of a few days ago, I've started to receive a large number of warnings (quoted below).  The library still seems to work fine, but these warning clutter and take over the code output space in the notebook.  I'm also worried this might lead to problems in the future.

A couple of other quirks - I can't replicate these errors in a brand new Notebook - it only happens in notebooks where I have been using this code for a while.  I open the note book, run my old code, and I have all these warning pop up that never occurred before.

- Describe the expected behavior:

The quoted warnings shouldn't show up.  And this was the behavior a few days ago - the code has not changed.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

```
WARNING: Logging before flag parsing goes to stderr.
W0619 13:39:13.702123 140186772047744 __init__.py:44] file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
W0619 13:40:03.861271 140186772047744 __init__.py:44] file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth`
```

**Comment by craigcitro** [comment]
This isn't really a colab issue -- pydrive is using a deprecated library (oauth2client), which is giving these warnings. Note that they should be nonfatal, just annoying.

I'd try reporting upstream to pydrive.
