### ISSUE TITLE
Google Colab Train Pytorch model save on Google drive, exit training midway, underlying folder is corrupted

### ISSUE THREAD

**Issue by karanchahal** [googlecolab/colabtools#791]
When I train a pytorch model on a google drive mounted colab notebook, it runs fine.

I can say weight periodically, however when I stop training midway to change some paramters, I can't access the underlying folder structure anymore.

Its says transport endpoint not connected 

The error message is
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.6/inspect.py", line 1490, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.6/inspect.py", line 1448, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.6/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.6/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.6/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.6/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by bharaniabhishek123** [comment]
I got same issue 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.6/inspect.py", line 1490, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.6/inspect.py", line 1448, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.6/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.6/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.6/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.6/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected

**Comment by temptitle** [comment]
Trained tensorflow model , got same issue
![Screenshot 2021-06-30 080839](https://user-images.githubusercontent.com/36921178/123917073-0c998000-d98b-11eb-94a1-8bf9cb7d58dd.png)

**Comment by temptitle** [comment]
Try to train tensorflow model , got same issue
![Screenshot 2021-06-30 080839](https://user-images.githubusercontent.com/36921178/123917192-2e930280-d98b-11eb-91f4-1d245d49371a.png)

**Comment by temptitle** [comment]
Try to train tensorflow model , got same issue

![Screenshot 2021-06-30 100846](https://user-images.githubusercontent.com/36921178/123917241-3d79b500-d98b-11eb-9b66-02b49e952633.png)

**Comment by craigcitro** [comment]
Can you provide a minimal repro notebook?
