### ISSUE TITLE
I stumped the AI and it kept hanging with no response

### ISSUE THREAD

**Issue by RealMayo** [googlecolab/colabtools#895]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: AI hangs and doesn't respond... > give gold to the king

You hand the king 100 gold pieces and he grins and nods approvingly. He turns
 back to the book and continues to read
> ask the king about the bandits
take the book from the king
revert
revert
Traceback (most recent call last):
  File "play.py", line 211, in <module>
    play_aidungeon_2()
  File "play.py", line 180, in play_aidungeon_2
    result = "\n" + story_manager.act(action)
  File "/content/AIDungeon/story/story_manager.py", line 181, in act
    result = self.generate_result(action_choice)
  File "/content/AIDungeon/story/story_manager.py", line 186, in generate_result
    block = self.generator.generate(self.story_context() + action)
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 118, in generate
    return self.generate(prompt)
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 118, in generate
    return self.generate(prompt)
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 118, in generate
    return self.generate(prompt)
  [Previous line repeated 17 more times]
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 109, in generate
    text = self.generate_raw(prompt)
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 92, in generate_raw
    self.context: [context_tokens for _ in range(self.batch_size)]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
KeyboardInterrupt
Game saved.
To load the game, type 'load' and enter the following ID: f7445a74-1891-11ea-abad-0242ac1c0002

- Describe the expected behavior: Expected the AI to respond in some way

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/github/nickwalton/AIDungeon/blob/master/AIDungeon_2.ipynb

**Comment by craigcitro** [comment]
AI dungeon is a third-party project, not supported by the colab team. If you find issues with the code, please report them at https://github.com/nickwalton/AIDungeon/
